### ISSUE TITLE
CI to package the app

### ISSUE THREAD

**Issue by martpie** [martpie/museeks#122]
- Adapt `.travis.yml`
- Adapt `build.js` so it can return an exit code: http://stackoverflow.com/questions/5266152/how-to-exit-in-node-js
- Add `ci:build` to npm scripts

**Comment by KeitIG** [comment]
On Linux, `electron-packager` can't package for windows if wine is not installed. We have to wait that:
- Windows is supported
- *or* Wine is supported by Travis

Blocked by https://github.com/travis-ci/apt-source-whitelist/issues/191

**Comment by YurySolovyov** [comment]
[AppVeyor](https://www.appveyor.com/) has windows support, so we might need to just tweak our build script to support different build targets.

**Comment by Thor77** [comment]
Maybe run linux + mac builds on travis and windows ones on AppVeyor?
Saw some other projects doing that.

**Comment by martpie** [comment]
Actually done 😎
