### ISSUE TITLE
m3u support for playlists (load/save)

### ISSUE THREAD

**Issue by kellertobias** [martpie/museeks#146]
It would be great and a good start for addressing #143 if the music import also could read m3u Playlists (and probably also other playlist files) (and naming them by the filename if there is no title present in the playlist)

this would make this player my number one choice for all except my main platform right now as it has excactly the functions I need do something like poweramp on android.

**Comment by KeitIG** [comment]
I did not know this file format, seems really interesting and I will investigate.

**Comment by BlueManCZ** [comment]
The `.m3u` file is plain-text file, which contains information about tracks, which are on playable medium like CD or something like that. 
![screenshot_20180404_180728](https://user-images.githubusercontent.com/17854950/38319809-11be0e90-3833-11e8-8fe8-f17fc290f561.png)

Here is what is inside:
```
#EXTM3U
#EXTINF:142,Two Steps From Hell - None Shall Live
01 - None Shall Live.flac
#EXTINF:178,Two Steps From Hell - Stormkeeper
02 - Stormkeeper.flac
#EXTINF:323,Two Steps From Hell - Victory
03 - Victory.flac
...
```

If you open this file, media player exactly know, which tracks can be loaded, can create temporary playlist and run it.

**Comment by KeitIG** [comment]
0.10 has been released, and this feature _looks_ quite simple. Will do next.

**Comment by KeitIG** [comment]
@kellertobias @BlueManCZ Would you like a "export playlist to m3u" feature too?

**Comment by kellertobias** [comment]
At the moment, I am using this player to play playlists that re exported from my main music player. So it is not necessary.

If it helps, I can provide a sample playlist.

**Comment by martpie** [comment]
I am currently working on this feature. I am getting one problem which is parsing these m3u files. Node.js cannot guess the encoding of a file, and package such as `chardent` gives wrong results...

I will have to figure out a way to guess the encoding of a `.m3u` correctly, or assume that all `.m3u` files are `URF-8` encoded... :/

**Comment by kellertobias** [comment]
You could ask the user on upload/ in the settings, which encoding the files will have.

**Comment by martpie** [comment]
Not really user-friendly ;) but I think I found a good technical solution

**Comment by martpie** [comment]
Got some good news.

![ezgif-1-7ba63631291f](https://user-images.githubusercontent.com/1311607/53589976-07488280-3b91-11e9-9f17-7bb56dcff90a.gif)

**Comment by martpie** [comment]
Done. I will gladly receive your feedback once it's release. I can also send you guys a pre-release so you can test it if you want.
