### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by YurySolovyov** [martpie/museeks#148]
We need this for stability and to prevent regressions.
Luckily, we already have a CI, so running tests is just one more command to run.

Things to discuss:
- where to start (might be a good idea to look into how other popular electron projects did this, and I know many didn't at all)
- testing framework and support libs (jasmine or ava, plus karma, sinon, also really need to look into [`spectron`](https://github.com/electron/spectron))
- how to test (need to separate main process tests and browser-side tests)

**Comment by KeitIG** [comment]
About the main-process and 0.6.2 app icon hotfix: the image folder was deleted by the build script. And when `nativeImage.createFromPath` was called, no warning was send. An error throw should have been put there to check if the image was not null.

I guess we can do that kind of things for the main-process multiple times.

**Comment by YurySolovyov** [comment]
> how other popular electron projects did this

Seems like [`Google-Play-Music-Desktop-Player`](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-) and [`Nylas N1`](https://github.com/nylas/N1) might be a good start

**Comment by YurySolovyov** [comment]
One more candidate to consider: [Jest](http://facebook.github.io/jest/)

**Comment by cfollet** [comment]
Jest looks awsome!

**Comment by KeitIG** [comment]
Unit-tests and test coverage are on my todo-list for the 0.10 release

**Comment by martpie** [comment]
Setup is done, tests just need to be written.
