### ISSUE TITLE
Command-line output for now playing?

### ISSUE THREAD

**Issue by fosspill** [martpie/museeks#194]
Hello!

It would be lovely to have some way of getting the currently playing track through command line (museeks --now-playing). 

Would this be possible to implement?

**Comment by YurySolovyov** [comment]
That should be doable, thought I doubt it would be implemented soon

**Comment by KeitIG** [comment]
@oleerik Would a command to run in the Chrome console be ok for you ? or do you really prefer in a native terminal ?

**Comment by oleerik** [comment]
@KeitIG Good question! The point would be to have an easy way to display currently playing music in the i3 status bar, for instance. I have no idea how I would go about showing data from the chrome console there but if that's possible then I don't see an issue with that :)

**Comment by KeitIG** [comment]
What do you call "the i3 status bar" ?

**Comment by oleerik** [comment]
It's an application that shows a tiny bar on the bottom ( or top) of your linux session with output from a script. Being able to do museeks --now-playing for instance and getting ARTIST - TITLE returned would make it possible to add the output there.

Now, this isn't a high priority request at all and, to be honest, might not even be needed for this application depending on what it aims to do.

If museeks purely aims to have a very minimalistic music playback experience with few extra functions (which would be absolutely lovely) then maybe it would be a better idea to not have functions like this one :)

**Comment by KeitIG** [comment]
That's an interesting idea, this joins the idea of a music player daemon + museeks single instance only. I'll keep that in mind.

**Comment by KeitIG** [comment]
Refs:
- https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md
- `process.argv`
- https://discuss.atom.io/t/how-to-pass-command-arguments-in-electron/17247/5
- If implemented, this implies we can always launch multiple instances of Museeks, so we may experience concurrency problems (with database or config)

**Comment by igorer88** [comment]
Maybe with mpris module implemented  @fosspill could test if the i3 status bar can fetch the current track from mpris.

**Comment by martpie** [comment]
mpris would definitely be the way to go so we don't re-invent the wheel 👍
