### ISSUE TITLE
Support cloud services for storage

### ISSUE THREAD

**Issue by mlanner** [martpie/museeks#304]
Museeks is great and it would be even greater if it could use a object storage backend, like OpenStack Swift or Amazon S3, for all the music. Then, it could either stream or sync (download) selected music directly from the cloud storage. If you need/want storage to test against, I'm happy to provide that and any pointers on how to use it.

**Comment by KeitIG** [comment]
Hello, thanks for the idea. I had it in mind for some times, but didn't want to post it since it will probably not be targeted for 1.0.

**Might** be possible with #260, if we get time and resources to achieve it.

**Comment by martpie** [comment]
So so so, now most storage system have apps proposing to stream files on demand (icloud, drive, onedrive...), the app works already ok with these, minus the small delay to download those file before playing them, so I'll leave it to the user to sync/stream their files to their filesystem, and Museeks can handle the rest.

**Comment by martpie** [comment]
(yes, 5 years later)
