### ISSUE TITLE
Need a way to tell which folders are already in the Library

### ISSUE THREAD

**Issue by YurySolovyov** [martpie/museeks#338]
New library UI is nice, but I struggle to estimate what's actually in my library ATM.

**Comment by KeitIG** [comment]
What if you remove some files? It's a bit hard to do now.

**Comment by YurySolovyov** [comment]
Well, let's assume we don't track that, for now just treat Library as source of truth here.
We can add re-scanning folders in the background later

**Comment by KeitIG** [comment]
I mean, I don't see the point:

- If you want to ensure a folder is scanned, just drop it again and new files will automatically be added
- If the user manually removes some files, everything goes wrong and it's biased

What is you usecase exactly?

**Comment by YurySolovyov** [comment]
Maybe it is just me, but I feel that something is wrong when I go to the library section and it only shows me "Add files" UI. 
![image](https://cloud.githubusercontent.com/assets/2168518/24674878/c8d49b30-1985-11e7-84f7-4f6fc1b90061.png)

I know I can go to library tab and my files will be there, but it is a bit different.
My point is that such list does not have to be really functional at this point, just give me some idea that my library is not empty.

For example AIMP show tree view on the left:
![image](https://cloud.githubusercontent.com/assets/2168518/24675041/5cbaa61e-1986-11e7-9c86-397512366d3a.png)

**Comment by vprigent** [comment]
Hi, the synced folders where present as a list some time ago. When the UI changed for what we have now, ( and a far better syncing system I have to admit ), the list goes out ...
I have a simple use case where I find it annoying. I have some new songs I want to play, I have to find the folder I already synced before, AGAIN, to get the new songs ... I usually have one single folder i'd love to be able to sync over and over

A simple list with the folder's name and path and two buttons to remove and sync should be enough :)

**Comment by KeitIG** [comment]
@vprigent Thanks for the feedback, what you can do is re-drop your music folder and only the new files will be scanned and added to your library.

Will have to look into this issue a bit more seriously though as more and more people are asking for it.

**Comment by DrEVILish** [comment]
The Library management page should contain a list of Folders that have been added to the "Library"
Next to each of the folders should have a "Refresh Icon", and "Trash Can".

Add a condition to the current addFunction that you can't add subFolders of an existing folder item to the Library.

"Trash Can" removes any items from the Library that are contained within this Folder.

"Refresh Icon" performs the same function as "Drag and Dropping" the folder back onto the library add box. Refresh function would have to ignore the previously mentioned addFunction.
