### ISSUE TITLE
Volume bar opens to left of volume icon and covers the play buttons

### ISSUE THREAD

**Issue by giorgosioak** [martpie/museeks#351]
**The volume bar opens at the left of the volume icon and covers the play buttons** until you move the mouse away. Sometimes you want to click pause you move your mouse over the volume icon and you need to make a second move to close the volume bar that pops up. Being on the right side of volume icon makes it more simple.

![screenshot from 2017-07-23 13-20-02](https://user-images.githubusercontent.com/8626050/28498607-bc42527a-6fa9-11e7-8565-a6239f4b76d6.png)
![screenshot from 2017-07-23 13-21-43](https://user-images.githubusercontent.com/8626050/28498621-0829e400-6faa-11e7-9d41-22860590f403.png)

My suggestion is to make it open at the right of the icon 😉 

**Specs**: 
Museeks 0.8.1 (Installed via AUR) -- OS: _Arch Linux_ -- Kernel: _x86_64 Linux 4.11.7-1-ARCH_

**Comment by KeitIG** [comment]
Hello @giorgosioak, thanks for the suggestion and the usecase problem well detailed. I will try to find a nice solution to this problem :)

**Comment by KeitIG** [comment]
Two quick mockups (poke @vprigent, @YurySolovyov). This is more what I had in mind. Just a few CSS tweaks.

![screenshot from 2017-09-08 13 50 57](https://user-images.githubusercontent.com/1311607/30210423-eec772da-949c-11e7-990b-321b560b8143.png)

![screenshot from 2017-09-08 13 51 41](https://user-images.githubusercontent.com/1311607/30210418-e8a25014-949c-11e7-9643-ddec4e38fc60.png)

**Comment by YurySolovyov** [comment]
Still 1 more interaction (click/hover) than needed.

**Comment by YurySolovyov** [comment]
One possibility I see is to rework header in a way that will allow us to place volume control below or above

**Comment by KeitIG** [comment]
One requirement that I have is: "in a 1920*1080 screen, Museeks minimum width should not exceed half of the screen width".

Having a look at @giorgosioak problem, it's just he cannot adjust volume then directly click an play/pause. It's not really that he has to hover the volume to show `VolumeControl`. Or am I wrong?

**Comment by giorgosioak** [comment]
@KeitIG Correct

**Comment by KeitIG** [comment]
From #423 by @lottanbettan

- a short delay (0.2 sec?) on hoover (volume button and timeline bar), would fix the "flickering" appearance.

**Comment by AntiGuide** [comment]
#509 seems like a good solution. Why isn't this getting merged?

**Comment by martpie** [comment]
Fixed this way in the end ![image](https://github.com/user-attachments/assets/3566c181-7564-48b7-84a8-34a7f26ca4dc)
