### ISSUE TITLE
Third-party integrations and APIs

### ISSUE THREAD

**Issue by martpie** [martpie/museeks#357]
This is a brainstorming about how to integrate third-party APIs/libraries in a distributed app.

#### examples

- Lyrics support #308 
- Support cloud services for storage #304 
- last.fm integration #231 

#### the problem

I have no experiences with that.
We need API keys for that, some are not free. Should Museeks provide API keys and try to get free access to this API arguing we are an open-source project? Should the user provide them?

**Comment by YurySolovyov** [comment]
IMO question should be IF this is museeks concern(s) at all. At the very least this should be up to plugin(s).

**Comment by KeitIG** [comment]
> IMO question should be IF this is museeks concern(s) at all. At the very least this should be up to plugin(s).

Right, it was more: "if we want that, how to do that?"

**Comment by martpie** [comment]
Closing this in favor of each individual issue.
