### ISSUE TITLE
Single-click play

### ISSUE THREAD

**Issue by Tarik02** [martpie/museeks#380]
I have an idea to add ability (optional, setting) to start music playing with single click (because i like this in nautilus file manager).

**Comment by KeitIG** [comment]
Hello, sorry for the late reply.

Thank you for the suggestion. I would like to some UX/interactions research about this first.

On Nautilus, how do you only select a file (without opening it)?

**Comment by a2nt** [comment]
What about an option to start playing music just after application start?
So I click museeks and it starts playing my music

**Comment by Tarik02** [comment]
@a2nt i think it may be, but only if music was playing when you closed player.

**Comment by KeitIG** [comment]
Let's discuss it on #397, these are two distinct issues.

**Comment by ldexterldesign** [comment]
Got nothing against the setting option but by default single click to play is poor UX IMO

Regards

**Comment by martpie** [comment]
I don't think I'll implement this one unless someone can come with a strong UX recommendation it is/can be a good idea.
