### ISSUE TITLE
Gnome Tray issues

### ISSUE THREAD

**Issue by a2nt** [martpie/museeks#389]
Here's tray icon with .resize({ width: 24, height: 24 }) at src/main-process/main.js:

![screenshot from 2018-02-06 19-07-14](https://user-images.githubusercontent.com/672794/35859167-9aea57bc-0b71-11e8-885d-272351a4e7e9.png)

Here's tray icon without resize function:

![screenshot from 2018-02-06 18-33-19](https://user-images.githubusercontent.com/672794/35859216-d0b49060-0b71-11e8-839d-e612790fce92.png)

I believe this function shall be removed. Let tray bar decide how to resize tray icon properly.

**Comment by KeitIG** [comment]
Thank you for the report, I will try to remove it and see how things go for on other Linux DE. (I suspect the Skype thing to be the same problem as the one I wanted to solve).

For the record on Pantheon, the tray icon was not being resized automatically.

**Comment by KeitIG** [comment]
@a2nt What are you using to display trays with the latest version of Gnome?

**Comment by a2nt** [comment]
it's vanilla Gnome Shell, Ubuntu comes with Gnome Unity by default, but u can install it using: sudo apt-get install gnome-shell

**Comment by a2nt** [comment]
ah checkout https://extensions.gnome.org/extension/495/topicons/

**Comment by a2nt** [comment]
we have a discussion here, guess it's the same issue: https://github.com/Foundry376/Mailspring/issues/648
Maybe it happens cuz of Gnome scaling 200% at QHD+ display, but Slack and WebTorrent works perfectly

**Comment by KeitIG** [comment]
ok, here's a list of the problems found so far:

- No tray on Ubuntu 17.10 without TopIcons gnome shell extension
- TopIcons tray doesn't work, you just see the icon with no context menu
- The tray icon is too small on QHD+

**Comment by a2nt** [comment]
Created API method at TrayManager.updateIcon(newIcon)
It can be used to update tray icon like play/pause.

Also fixed Gnome-Shell issue:

Gnome icon will be resized to 24x24 like it was originally, after that of platform is Linux and gnome-shell is running tray icon will be changed to good one.

It happens in less than second so no one will notice glitch.

Right button click context menu works ok for me, there's: current song, play/pause, previous, next, show, quit

**Comment by KeitIG** [comment]
@a2nt Could you please try the `hidpi` branch and tell me if the Tray looks fine or not? I tested on my MacBook with Virtualbox but I see a blurry icon. I do not know if this is because of Virtualbox or not.

**Comment by martpie** [comment]
After some research, I have decided to kill the tray feature. See my rationale in #686 :)
