### ISSUE TITLE
Improve styles codebase 

### ISSUE THREAD

**Issue by martpie** [martpie/museeks#398]
The currect styles have multiple problems

- [x] Drop Sass for Stylus or PostCSS to avoid non-js binaries [open discussion]
- [x] Remove all nesting in selectors
- [ ] Stricter lint rules
  - [ ] More variables/mixins
  - [ ] 6 digits colors
  - ...
- ...

**Comment by YurySolovyov** [comment]
Use native CSS variables?

**Comment by KeitIG** [comment]
Pure CSS is a decent option today indeed

**Comment by YurySolovyov** [comment]
I'm talking about pure css variables for now, I still like the ability to nest stuff (a-la sass/less/stylus etc.) and I don't think css allows that ATM

Just to be clear.

**Comment by KeitIG** [comment]
Nesting is a not a must-have feature imho, it leads to potential terrible code (e.g the current one)

**Comment by YurySolovyov** [comment]
There are 2 ways you can go: forbid nesting and use pure css or just be disciplined in using nesting and don't go nuts with it. I prefer 2nd option
