### ISSUE TITLE
Exception thrown so library scan stops and never completes

### ISSUE THREAD

**Issue by guzzard** [martpie/museeks#413]
```
module.js:472
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Applications/Museeks.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as dialog] (/Applications/Museeks.app/Contents/Resources/electron.asar/browser/api/exports/electron.js:35:14)
    at process.<anonymous> (/Applications/Museeks.app/Contents/Resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:300:26)
```
![image](https://user-images.githubusercontent.com/9007314/37150457-08a58e80-22d2-11e8-85ed-00fd1ec3ec99.png)

**Comment by KeitIG** [comment]
Hello @guzzard !

Thank you for the report, what version of Museeks do you use? v0.9 is about to be released (today), do you want to try it and see if you can reproduce this bug?

**Comment by KeitIG** [comment]
I actually just released it https://github.com/KeitIG/museeks/releases

**Comment by guzzard** [comment]
Hi @KeitIG, I was trying 0.81 on Mac OS X. Testing new version 0.9 now, will report back with results (will take some time to scan..).

**Comment by guzzard** [comment]
@KeitIG, no error this time, but I quit the app after about 2 hours of scanning the library (25k+ over sshfs). When I started the app again, the scan did not resume however, and I cannot find any way to manually resume the scan. Would that be possible to add?

**Comment by KeitIG** [comment]
@guzzard ok 👍 

A few things here:

- large libraries: I never tried Museeks with this amount of tracks, you might encounter some slowdowns
- folders mounted over the internet: I never tried it, this could explain why it is this slow
- resume scan: some tracks should be your library already (no?), try to re-import your folder, duplicates won’t be imported again

**Comment by guzzard** [comment]
@KeitIG resuming the scan by just adding the folder again seem to work 👍 

However, looking at the network traffic, it looks like the whole files are read? That must be the reason why the scan takes such a long time (even at 12MB/s). It should be enough to read the start and end of MP3 files to get the ID3 tag?

**Comment by KeitIG** [comment]
Ah, interesting indeed! I think we need to read the whole file to get the song duration.

Maybe there is a way to know it without reading the whole file

**Comment by KeitIG** [comment]
Thank you very much for your help 🙌

**Comment by guzzard** [comment]
@KeitIG Yeah, seems like it's possible to calculate the length from header data + file size?

https://stackoverflow.com/questions/23776115/get-mp3-length-in-c

I know other players are scanning the library and getting ID3 + length without reading the whole files, gmusicbrowser and Quod Libet are two examples.

**Comment by KeitIG** [comment]
So apparently yes, it seems like a new thing in `musicmetadata` https://www.npmjs.com/package/musicmetadata#api (last point) (at the time, I donot think this option existed).

I will try to integrate this change and see how it affects things.

**Comment by guzzard** [comment]
Awesome! Should speed things up considerably locally, and make internet mounted folders usable as well! 👍

**Comment by KeitIG** [comment]
@guzzard Do you have an email address and an OS so I can send you a test binary?

**Comment by KeitIG** [comment]
@YurySolovyov Are you aware of any downside with `Promise.promisify` in terms of performances? I do not see a lot of differences after implementing these changes.

**Comment by YurySolovyov** [comment]
No, not really.
That said, I'd probably consider dropping bluebird at some point, cause native promises + async/await are going to be the future and there are [native node API](https://nodejs.org/api/util.html#util_util_promisify_original) for promisification, as well as [community modules](https://github.com/sindresorhus/pify) that use native promises under the hood

**Comment by denikris** [comment]
problem still exist in version 0.9.x deb file

**Comment by KeitIG** [comment]
We switched to a new package to scan id3 tags in 0.9.1, can you test it and tell me if it is reproducible?

**Comment by guzzard** [comment]
@KeitIG tested today with 0.9.4 and the issues seem to be there still. Still seems like the whole file is read, and not only the id3-tag bytes.

**Comment by KeitIG** [comment]
This is normal because we need that to get the song duration. I’ll try to investigate soon.

**Comment by guzzard** [comment]
@KeitIG I thought you would change to `musicmetadata` and read the `TLEN` value from id3v2 as per your comment on the 9th of March?

**Comment by KeitIG** [comment]
The problem is not all files use id3v2. I just need to wrap my head around, and we can most probably improve things a bit, but I really do not get the error you get.

**Comment by martpie** [comment]
Doing some cleaning, if it still happens in the latest release, please poke me and I'll re-open it :)
