### ISSUE TITLE
PageUp/PageDown and Home/End key pairs only work once

### ISSUE THREAD

**Issue by YurySolovyov** [martpie/museeks#416]
After library got scrolled, you need to select track again to scroll more

**Comment by KeitIG** [comment]
Can you show a screencase or something? I cannot reproduce it

**Comment by YurySolovyov** [comment]
1. start playing track from the above of the library
2. press PageDown - it scrolls
3. press PageDown again - nothing happens

**Comment by KeitIG** [comment]
I initially thought it was due to `react-custom-scrollbars`, but those events work fine on their demos. I'll continue investigating.

**Comment by YurySolovyov** [comment]
I think this is an issue again. At least on Ubuntu 18.04

**Comment by martpie** [comment]
I cannot reproduce it on macos, I'll check on Ubuntu

**Comment by martpie** [comment]
Doing some cleaning, if it still happens in the latest release, please poke me and I'll re-open it :)
