### ISSUE TITLE
Audio by Directories

### ISSUE THREAD

**Issue by DmitrySkibitsky** [martpie/museeks#422]
People who listen to music often sort it by directories. Why does nobody add this structure to the audio players? I have +4k songs and a lot without tags. It's not practical to use the application.

**Comment by KeitIG** [comment]
Hello :)

Could be an interesting addition to (or duplicates of) #130

> Why does nobody add this structure to the audio players

Because this very usecase is quite uncommon, and the complexity to implement that really hard: Museeks is a  Another way to solve it could be to have a context menu in Nautilus/Finder/whatever to play all tracks in the current folder.

**Comment by KeitIG** [comment]
_and no need to be rude, if you don't like the app, feel free to uninstall or fork it._

**Comment by YurySolovyov** [comment]
Not sure if it is (un)common, but I use it a lot in other players (not museeks everywhere yet, sorry)

**Comment by KeitIG** [comment]
@Yury, do you have player names so I can check how they achieve this?

**Comment by yury** [comment]
cc @KeitIG  @YurySolovyov

**Comment by YurySolovyov** [comment]
@KeitIG http://www.aimp.ru/ (see EN language toggle at the top)

**Comment by DmitrySkibitsky** [comment]
@KeitIG , I do not think this app is bad. Just this I do not have enough in the players. Take the same deepin music, or Lollipop ... They have a maximum of Executors, Albums, etc. but nobody does the directory structure. For me, this is the most important thing.

**Comment by KeitIG** [comment]
The idea makes sense. How do you usually organize your library @DmitrySkibitsky?

I personally have something like `music/artistslists/albumslist/trackslist`

**Comment by KeitIG** [comment]
On the technical part, we might want to go back to what we had before, with folders added to the library.

Related to #338.

Some of the problems:

- circular references / symlinks
- how to display these (just a file explorer)?
- ...

**Comment by YurySolovyov** [comment]
One tricky part I can see in implementing this is how to get parent dir nicely.
For 99% of cases we can "just" grab the parent dir and that will be correct:
```
/music/Album-name/1.mp3
/music/Album-name/2.mp3
/music/Album-name/3.mp3
/music/Album-name/4.mp3
/music/Album-name/5.mp3
/music/Album-name/6.mp3
/music/Album-name/7.mp3
```
in that case you get `Album-name` and you're done.

But.

there are cases like:
```
/music/Album-name/CD1/1.mp3
/music/Album-name/CD1/2.mp3
/music/Album-name/CD1/3.mp3
/music/Album-name/CD1/4.mp3

/music/Album-name/CD2/1.mp3
/music/Album-name/CD2/2.mp3
/music/Album-name/CD2/3.mp3
/music/Album-name/CD2/4.mp3
```
And I'm not sure what's the good heuristic for getting `Album-name` in that case.
Maybe just take everything between filename and root directory for the music dir:
`Album-name/CD1` and `Album-name/CD2` ? :man_shrugging:

**Comment by DmitrySkibitsky** [comment]
@KeitIG, At me it is similar. But do not attach nesting to a specific value. Simply banal "Directory structure" After all, somewhere there is a path to the audio file in some file "all_files.db" Draw the directory structure, and then click on the path to "output audio," go through all_files.db and compare . Sounds easy))

**Comment by YurySolovyov** [comment]
(follow-up to my prev. post)
Or, we can treat all folders inside root as albums regardless how files are stored inside:
so that for
```
/music/Album-name/CD1/1.mp3
```
we just take `Album-name` as folder name and scan everything inside recursively

**Comment by DmitrySkibitsky** [comment]
I just do not know how it works. I just introduced.

**Comment by DmitrySkibitsky** [comment]
@YurySolovyov , By clicking on the "Structures" item, there must be a full path. Otherwise, what you are talking about is confusion in the same names.

**Comment by FinlayDaG33k** [comment]
I also would like this functionality to be added.
The music player (Blackplayer EX) on my phone has it and the Plex app has it.

I personally sort my music like `/music/genre/<artist or band> - <album name> (<year>)/<artist or band> - <title>.<ext>`.
It makes it a lot easier to find a specific one I want since I know where to find it at all times (without having to remember the name of the track, I just go like: "this artist, this album, this number in the list... ah so that was it's name"), which is especially helpful considering I do listen quite a bit of J-pop (so remembering, let alone typing the names is kinda difficult).

**Comment by igorer88** [comment]
@YurySolovyov, @martpie  
How about to create independents music libraries, 
for example: 
- `Music/<Lib name>/<artist or band>/<album>` 
- `Music/OST/<movie>`
- `Music/Recordings/<song title>`

**Comment by martpie** [comment]
Closing. I've give it some thoughts and TL,DR, I won't implement it:

- We should not make assumptions on how the library of people is organized, the software should work the same if someone has all his tracks in one folder, everything nicely organized or something chaotic.
- #130 will be a way to get there
- It's useless to re-implement a file manager withing Museeks, if you want to use your library like that, we should implement #154,  so you can use your favorite Finder/Nautilus/Whatever and play your tracks from there :)
