### ISSUE TITLE
Feature Request: Media button functionality

### ISSUE THREAD

**Issue by codedcosmos** [martpie/museeks#431]
I have switched over from rhythmbox and so far it has been great. My only issue with Museeks is that I have to switch to the workspace I put my music player in and click a button when I want to pause or skip a song. Adding the ability to press the play/pause/skip etc buttons on my keyboard would be a great feature for me and would pretty much make Museeks perfect for me.

tldr: Add the ability to use keyboard media buttons like play, pause and skip into Museeks.

**Comment by KeitIG** [comment]
Hello! :)

Media controls « should » be working: https://github.com/KeitIG/museeks

Can you share the model of your laptop/computer/keyboard?

**Comment by codedcosmos** [comment]
Oh sorry, I must be a edge case, I forget you guys support more than just Linux. I am using a cougar 600k keyboard on arch Linux 64 bit with gnome. 

Thanks for the quick reply!

**Comment by KeitIG** [comment]
And can you confirm those media keys work with other players? Maybe this is an issue with Electron/Chromium itself... Looks similar to #365 though

**Comment by codedcosmos** [comment]
They work with VLC and rhythm box from memory but I will test chromium shortly. .

**Comment by codedcosmos** [comment]
It doesn't appear to work with chromium/firefox with youtube but I am not sure if that's normal. I check #365 and yes those are the sorts of buttons I am using. If you would like I can send a screenshot or a log file.

**Comment by KeitIG** [comment]
I just found that https://github.com/electron/electron/issues/5268

> @Limero Linux keys are by default stolen by dbus.

As it looks like a specific linux problem, maybe I should investigate this way.

**Comment by BlueManCZ** [comment]
I'm using Debian 10 with newest KDE Plasma and each media player (Rhythmbox, Clementine, Banshee) has integration with backend media player [Phonon VLC](https://community.kde.org/Phonon). When I run a song, in system tray I can see this popup window, which can control the media player and works great with keyboard control keys.

![screenshot_20180404_153432](https://user-images.githubusercontent.com/17854950/38311548-be7a25c4-381f-11e8-83f1-3258e1d71d1a.png)

Museeks doesn't have this integration, so maybe one way how to solve this, is trough this Phonon feature.

**Comment by KeitIG** [comment]
It might be related indeed, I worked a bit on #93 Mpris support and it looks really similar. I think I should be able to implement that for 0.10.

**Comment by BlueManCZ** [comment]
Also integration with default system apps would be great. (Open file with.., Set app as default for this file extension..) :blush: But this is for another thread.

**Comment by KeitIG** [comment]
https://github.com/KeitIG/museeks/issues/154 #https://github.com/KeitIG/museeks/issues/155 ;)

**Comment by codedcosmos** [comment]
My guess is that it is electron that is the issue.

**Comment by codedcosmos** [comment]
Took a while for the AUR to update:
https://aur.archlinux.org/packages/museeks-bin/

but it is still an issue even though the patch notes list:
> Fixed playback:previous event not working from Tray or Dock menu

**Comment by KeitIG** [comment]
This patch note is unrelated to this problem ;) I will try to investigate today what causes this.

**Comment by codedcosmos** [comment]
Oh ok. Cheers

**Comment by codedcosmos** [comment]
Small Update: The media buttons work on the KDE plasma desktop but not gnome.

Unfortunately I have no idea why.

**Comment by martpie** [comment]
After some investigation, it looks really similar to https://github.com/electron/electron/issues/10159, I plan to integrate mpris soon (https://github.com/martpie/museeks/issues/93 one of the oldest issues), like for the next release.

Let's see if it fixes this problem!

**Comment by martpie** [comment]
This seemed to have been fixed in Electron 3.0.2. So it should be fixed in the next releast.
