### ISSUE TITLE
Add an option to hide the tray icon

### ISSUE THREAD

**Issue by lottanbettan** [martpie/museeks#447]
Wishing the tray icon to disappear in macOS :)
Cheers!

**Comment by KeitIG** [comment]
Here are a few thoughts to be considered:

- We should merge this with the existing Tray option
- I am not sure if it makes a lot of sense to have the Tray on Windows, I didn't see any other music player doing it
- I use tray quite a lot on macOS, an option to hide it is the way to go
- There are currently issues with Tray on Linux (at Electron-level), relying on Tray for user-behavior is not safe.

**Comment by lottanbettan** [comment]
An option to hide it would be the best! Or an option to show it, if it's hidden by default - which would be the very very best! :)

**Comment by martpie** [comment]
Will do for next release.

**Comment by martpie** [comment]
On macOS, the tray will now always be disabled.

**explanations: ** the default behavior when closing an app on macOS is to hide the window, but the app is still theoretically running. Which is exactly the problem the tray was trying to solve. Therefore, the tray is not needed as the dock icon fulfill the same role. (node: you can also control the playback from the dock icon).
