### ISSUE TITLE
Ctrl-click on macOS should not trigger a track selection

### ISSUE THREAD

**Issue by jdbevan** [martpie/museeks#453]
macOS Sierra 10.12.6

It's hard to add lots of tracks to a playlist because they can only be adding one-by-one. Right-clicking on multiple selected items deselects all but the one track you right clicked on.

**Comment by KeitIG** [comment]
You have multiple way to improve that:

- cmd+click should toggle a track for selection
- shift+click select all tracks between the last selection and the new one.

Tell we me if it helps :)

**Comment by jdbevan** [comment]
Ah I just realized what I was doing.

I SHIFT+clicked several tracks and then CTRL+clicked on the selection because my mouse does not have a right click button.

The CTRL+click gets interpreted as a regular click instead of a right click.

**Comment by KeitIG** [comment]
On Mac, should ctrl-click display the context-menu?

**Comment by jdbevan** [comment]
Yes: https://support.apple.com/en-us/HT207700

**Comment by KeitIG** [comment]
Then it's a bug, thank you for noticing it :)

**Comment by KeitIG** [comment]
Oh I see the problem, it should be easy to fix.

**Comment by martpie** [comment]
Fixed in ead5ce0
