### ISSUE TITLE
Re-think Tray, close behavior and frame

### ISSUE THREAD

**Issue by martpie** [martpie/museeks#457]
I think the current way of closing the app on Window / Linux is bad UX. Also, the topbar does not bring anything (it was a workaround to add the minimize and the maximize buttons).

### MacOS

- The current behavior is correct: closing the app actually "hides" it, to close the app, press cmd-Q or or right-click the dock + "Quit".
- The inner frame is great
- The tray is not that useful if media keys are working

### Windows

- The app should close and quit on "close" (like the default Window music app)
- The custom frame does not provide anything great
- The tray is useless (?)

### Linux

- Not sure about the correct behavior on close https://twitter.com/KeitIG/status/1031222794326081536
- The custom Frame does not bring much too
- The Tray is not useful, mpris should be used instead #93 

## Actions

These are light conclusions, I am open to discussion.

- [ ] **To be discussed** Disable the Tray module everywhere (keep it in the codebase just in case)
- [ ] **To be discussed**  Adapt close behaviors on Windows and Linux
- [x] Use native frame on Windows and Linux

**Comment by KeitIG** [comment]
Native frame is now used everywhere 22d7e28

**Comment by Aaahh** [comment]
I mean the tray could be a fallback on linux installs that do not support mpris
Also, being able to close the window without stopping the music is very nice

**Comment by igorer88** [comment]
The Linux user should elect to activate the tray or not.

**Comment by martpie** [comment]
And so do all users for all platforms. It should not be too hard to implement and there is a certain demand for this feature, so I'll implement it.

**Comment by martpie** [comment]
The tray is now only showed when the window is hidden. An option was added to the dock menu to force-quit the app in case of tray not working in for some DE.

When mpris will be working, I will need to add an option to fully disable the tray, to avoid a duplicate icon in the topbar on Linux.

**Comment by igorer88** [comment]
If anyone has a Gnome 3 DE (like Ubuntu uses) please just open Rhythmbox play something and close it. How does it behave? It closes right away? or it continues playing?

I do have Cinnamon 4 (I'm using Linux Mint) so it includes a closing button. So I can't test that feature. In Cinnamon, Rhythmbox keeps playing the song with the app closed.

When I was integrating mpris-services it worked perfectly so I didn't need the tray.

**Comment by Aaahh** [comment]
Yeah so the music keeps going and rhythmbox just minimizes to the calendar
drop down

**Comment by igorer88** [comment]
Ok, and it doesn't have a close button? Or it has to be open and then stopped in order to close the app?

**Comment by Aaahh** [comment]
Opened to close
