### ISSUE TITLE
[Enhancement] Colors from GTK theme on Linux

### ISSUE THREAD

**Issue by varlesh** [martpie/museeks#459]
Maybe it's possible add support or option use system colors for application?
It's will be good looking on single style on OS...
or maybe option set custom colors:
![image](https://user-images.githubusercontent.com/8083855/44440927-62def580-a5db-11e8-8783-af434121709f.png)

**Comment by KeitIG** [comment]
Hello 👋

I was thinking about adding support for choosing a primary color, but I have no idea how to apply a full theme as Museeks is not built on GTK.

Somewhat related to #162

**Comment by YurySolovyov** [comment]
There are some [OS-specific APIs for getting theme-related info](https://electronjs.org/docs/api/system-preferences#methods), but nothing for Linux, so for that feature to be implemented, we need a Linux part of these to be implemented (where it makes sense).

**Comment by igorer88** [comment]
We can get the current theme with this.
`gsettings get org.gnome.desktop.interface gtk-theme
`
 Maybe we could think on a workaround?

**Comment by YurySolovyov** [comment]
I wonder if that's available via dbus.

**Comment by martpie** [comment]
I won't implement it, as one cannot ensure the quality of the UI (borders, contrast...) meet accessibility standards, but #162 should be a way to get there :)

**Comment by martpie** [comment]
sidenote: I am planning on implementing a "main color chooser" for people who want to update the blue to something else.
