### ISSUE TITLE
Cannot start app - A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by nedkellddv** [martpie/museeks#460]
When I try to start either the AppImage or the deb file I get:

A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from #<Object>
    at /home/nedkelly/opt/Museeks/museeks-amd64/resources/app.asar/dist/main/bundle.js:1:20947
    at App.<anonymous> (/home/nedkelly/opt/Museeks/museeks-amd64/resources/app.asar/dist/main/bundle.js:1:21163)
    at emitTwo (events.js:131:20)
    at App.emit (events.js:214:7)

I am trying to run this on linux mint 17.3

**Comment by KeitIG** [comment]
Hello @nedkellddv,

I just tested Museeks 0.10 on KDE Neon (AppImage 64bits), it works well, can you give me more informations regarding your distro, which version of Museeks you used and the 32/64 bits version? :)

**Comment by joshbedo** [comment]
Just had the same issue on mac was wondering if the app is broken

**Comment by martpie** [comment]
@joshbedo Any reason why you are not using the DMG? Does it happen with it too?

If you use the advanced build way, can you make sure your branch is not outdated? Can you delete the directory, re-clone and re-build the app?

I may have an idea of what is causing it, but I forced-push against the commit introducing this bug (yes, on master, bad me)

**Comment by nedkellddv** [comment]
well I do not know if it has something to do with different Linux (Mint) versions?

**Comment by martpie** [comment]
@nedkellddv Did you install the 32 or the 64 bits? And which version did you use?

**Comment by codedcosmos** [comment]
This issue is also happening for me on Ubuntu 18.04 64 bit deb install:


### A JavaScript error occured in the main process

```
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from #<Object>
   at /opt/Museeks/resources/app.asar/dist/main/bundle.js:1:20947
   at App.<anonymous> (/opt/Museeks/resources/app.asar/dist/main/bundle.js:1:21163)
   at emitTwo (events.js:131:20)
   at App.emit (events.js:214:7)
```

**Comment by martpie** [comment]
Thank you for all the reports, 

I rebuilt the app here: https://drive.google.com/open?id=1HveA5VH7Q41DC4-bvVRAph7SctX1RBr3

could you try to download your corresponding package and tell me if you encounter the same problem?

**Comment by martpie** [comment]
https://github.com/electron/electron/issues/7657 this is interesting, but it does not explain why I don't get this error on fresh installs of Ubuntu

**Comment by codedcosmos** [comment]
Tried installing it (without uninstalling it), then tried again (after uninstalling museeks) the issue (for me at least) still persists. I will try a reboot and see if anything changes.

**Comment by martpie** [comment]
Found the error, working on a hotfix right now

**Comment by martpie** [comment]
@codedcosmos Can you apply what is there: https://github.com/martpie/museeks#troubleshooting and tell me if you can reproduce it?

**Comment by martpie** [comment]
Can you guys confirm that this version works for you? https://drive.google.com/drive/folders/1n003sLkjz4_4NZ4ecXFgrh3TmifXJ7Za?usp=sharing

**Comment by codedcosmos** [comment]
The newer build works for me. (Ubuntu 18.04 almost fresh install (installed 2 days ago))

**Comment by martpie** [comment]
Thank you for helping me debug that pesky bug :)

0.10.1 released

**Comment by nedkellddv** [comment]
Hi 

Thanks for making this app, and for fixing this bug :)

0.10.1 amd_deb64 and Appimage64 works on Linux Mint 17.3 as well
