### ISSUE TITLE
hotkeys

### ISSUE THREAD

**Issue by DennisDray** [martpie/museeks#466]
the keyboard play/pause, next/ previous buttons should control the player
also, a panel indicator with those controls would be great, like panflute had it back in the day
handy when your laptop is in tablet mode

**Comment by martpie** [comment]
Playback hotkeys should be working. What is the laptop/PC you are using?

I don’t get the panel indicator thing, so you have a screenshot or more details for me please?

**Comment by martpie** [comment]
Let’s assume it’s a duplicate of 
https://github.com/martpie/museeks/issues/431.

Feel free to contest.
