### ISSUE TITLE
Import/Export Playlist Files

### ISSUE THREAD

**Issue by irfanfadilah** [martpie/museeks#467]
I'm using dual-boot OS, Ubuntu and Windows. Managing playlist on different OS and music player is annoying, then I came to this music player.  *The music files are in same location on both OS.

Is there anyway I can export playlist file and import it? I saw there's some folders in config directory. Can I just copy files containing playlist data and paste it on different Museeks instance in other OS? If yes which files?

Thanks,

**Comment by martpie** [comment]
Simple answer: no (for now)

So the thing is tracksarestoredin a DB, and tracksIDs may be different on your different OS, so we cannot know "which track is the same".

That said, I think an m3u import/export feature with relative paths could resolve your issue in a quite elegant way.

See https://github.com/martpie/museeks/issues/146

(I would love to work on this feature next, but I'm a bit busy these days)
