### ISSUE TITLE
When minimize to tray setting is active, opening/closing the app causes multiple instances of tray icon to appear

### ISSUE THREAD

**Issue by YurySolovyov** [martpie/museeks#479]
OS: Ubuntu 18.04
Extensions:
![image](https://user-images.githubusercontent.com/2168518/55470946-61fe4f80-5611-11e9-9a33-defd503d09f4.png)
Tray:
![image](https://user-images.githubusercontent.com/2168518/55470841-1ea3e100-5611-11e9-993b-d6a8105f3b7b.png)
Where only the leftmost is actually responding to actions.

**Comment by martpie** [comment]
mmmh could there be something wrong here? https://github.com/martpie/museeks/blob/master/src/main/modules/tray.ts#L159-L165

**Comment by YurySolovyov** [comment]
Dunno, I wish there was `.ensure` method...

**Comment by igorer88** [comment]
What happens when you restart gnome? (I think that the manager is called gnome-shell)
They're still present?

**Comment by BlueManCZ** [comment]
The bug is still present. I've never seen an app that would create a tray icon when closing the window. The tray icon is always initialised on the application startup and stays there until the process is terminated. Maybe you could do the same here, but initialise the tray icon only when the user opts for it in settings?

**Comment by martpie** [comment]
You're actually right, maybe we should try to not be smart about it and always display it 🤔

**Comment by igorer88** [comment]
Maybe we could handle it better with the Rust migration.  Since is an electron error.

**Comment by martpie** [comment]
The rust migration is staling right now because we are missing a context menu API :( but yeah it should help.

I contacted the Tauri team, and they told me it was definitely on their roadmap, but it was a very complex thing to implement.

**Comment by martpie** [comment]
After some research, I have decided to kill the tray feature. See my rationale in #686 :)
