### ISSUE TITLE
sort to most recently added tracks

### ISSUE THREAD

**Issue by stax76** [martpie/museeks#480]
Hi,

I've programmed a windows video player called mpv.net in the last two years and I'm looking for a new project now in order to learn a new programming language. I'm watching a lot of TV shows and listen a lot to music so video and audio playback software is the software I'm using the most often and I've the most interest in.

Typescript is on the list of languages I want to learn and I also want to learn how to use Visual Studio Code. Regarding web tech I'm more or less a beginner and I've decided to learn it in my next project.

Typically, I listen to music that I've discovered just recently so in MusicBee I added a column 'Date Added' and sort to this column. I was thinking how to achieve this in Museeks, it's not having a 'Date Added' column (or column of file creation date) so I was thinking that I can create a m3u playlist and import it in museeks but it's not working, I've saved the m3u playlist in the same folder where my music is located and used the 'Import Music' feature in the settings, it's finding and creating the playlist but the playlist is empty which appears like a bug. I don't see any way in museeks to listen to my most recent music, is there anything else I could try to just listen to my most recent music?

**Comment by martpie** [comment]
Hello 👋 

It goes a little bit in direction of #440. #401 would solve it as well; I will close it as duplicate :)
