### ISSUE TITLE
Section when you library divided by folders or filter library by folder, to easily navigate

### ISSUE THREAD

**Issue by nrudnyk** [martpie/museeks#481]

**Comment by martpie** [comment]
I will need to understand your usecase more in detail to understand your actual need 😄

How do you usually use a music player?

**Comment by nrudnyk** [comment]
I don't want to create playlists, because I've already sorted music out locally, and could easily filter albums\artists by folder.
So imagine, feed all your music library to the app, and later, you can select one folder from the hierarchy, and only tracks from that folder and it's subfolders will be visible in the (as of now) library view. E.g, you have 
music
---artist#1
------album#1
------album#2
---artist#2
....

soi f you select artist#1 it shows all tracks from album#1+#2, if you select album#1-  it shows only that album and so on

P.S. - Usually I listen to music over there :)

**Comment by YurySolovyov** [comment]
Related: #338 #422 #130

**Comment by martpie** [comment]
Let's close this in favor of those then
