### ISSUE TITLE
Feature request: Prevent laptop from sleeping

### ISSUE THREAD

**Issue by pjebs** [martpie/museeks#487]
1. I was wondering what library you were using to play the sounds.
2. I was wondering if a setting could be made to play sounds by preventing laptop from sleeping: 
https://github.com/newmarcel/KeepingYouAwake
https://github.com/iccir/Fermata

**Comment by martpie** [comment]
This software being based on Electron, the library used to play sounds is different for each operating system (win, mac, lin)

**Comment by pjebs** [comment]
Can you tell me where in the code you dou play music and disable sleep?

**Comment by martpie** [comment]
https://github.com/martpie/museeks/blob/master/src/ui/lib/player.ts

https://github.com/martpie/museeks/blob/master/src/main/modules/sleep-blocker.ts
