### ISSUE TITLE
Shift + Down Arrow - Select

### ISSUE THREAD

**Issue by DrEVILish** [martpie/museeks#489]
Shift + Down Arrow should select the current track and the track below it and so on for as many presses of the down arrow.

Prioritise keyboard shortcuts over mouse clicks. 💃

**Comment by martpie** [comment]
Should not be too hard to implement and looks like a default in a lot of file exporers, let's do this then!

**Comment by martpie** [comment]
Done in https://github.com/martpie/museeks/pull/497

**Comment by ldexterldesign** [comment]
> Prioritise keyboard shortcuts over mouse clicks. 💃

**Comment by martpie** [comment]
> Prioritise keyboard shortcuts over mouse clicks.

Not sure to get this one 🤔

**Comment by ldexterldesign** [comment]
?

**Comment by martpie** [comment]
I mean, is it done or are you expecting more?

**Comment by ldexterldesign** [comment]
Issue seems resolved as OPs request tests fine for me 👍

I think my comment was a general aside

Feel free to close issue

Regards
