### ISSUE TITLE
Suggestion: Easy Way to Tell What Song Is Playing on Computer

### ISSUE THREAD

**Issue by OpWinterStorm** [martpie/museeks#492]
Hey, just downloaded this recently, it seems like a very nice music player!  One suggestion I have is to make a way to easily tell what song is playing without opening the player.  I've seen a few apps do this a few different ways; either by having a banner appear somewhere on the screen when the song changes, by showing what song is playing when the volume changes, or letting the user hover the mouse over the program and showing it as the title.

Thanks!

**Comment by MrDoctorKovacic** [comment]
Hi, have you tried Settings > Interface > Display Notifications ?

**Comment by OpWinterStorm** [comment]
Yes, I have that box checked, but when the song changes or I change the volume it doesn't show anything.  What event should cause the song to pop up?

**Comment by martpie** [comment]
What is your OS?
