### ISSUE TITLE
checksum

### ISSUE THREAD

**Issue by linsui** [martpie/museeks#493]
Could you please add checksum for the release?

**Comment by martpie** [comment]
Should the checksum be run against the whole file? I don't have a lot of experience with those

**Comment by linsui** [comment]
Sorry, I don't know how to do... Just hash of each installer is enough. Thanks!

**Comment by igorer88** [comment]
Yes, @martpie just get the hash from each package. MD5, and/or SHA-1 would be enough.

**Comment by linsui** [comment]
I prefer to get sha256/512 because sha1 is not safe anymore. You can calculate them with 7-zip, but I guess there are some better way to calculate checksum automatically when build.

**Comment by martpie** [comment]
Related: build binaries on CI. I don't see myself doing this error prone / manual work every release 🤔

**Comment by linsui** [comment]
Found an example, may help. https://github.com/VSCodium/vscodium/pull/120/commits/33bc3b2f8be18a2fe426fab9769bacf6f916d2a2

**Comment by linsui** [comment]
Eletron builder can generate checksum in latest.yml automatically. See https://www.electron.build/configuration/publish

**Comment by martpie** [comment]
256 checksums will added from 0.11.2 release.

**Comment by linsui** [comment]
Thanks!
