### ISSUE TITLE
New playlists dont show tracks until renamed

### ISSUE THREAD

**Issue by jdbevan** [martpie/museeks#494]
macOS Mojave v10.14.5

Museeks 0.11.0

I can reproducably select some tracks, right click, create new playlist, then navigate to the playlist and no tracks are displayed. Once I've right clicked on the playlist name and renamed it, then the tracks appear. The recording below contains a word in the search box in the top-right which I thought might be the source of the bug, but I see the same behaviour with an empty search box

![museeks-new-playlist](https://user-images.githubusercontent.com/1391574/60670510-c4612900-9e68-11e9-8b66-2e9dfa116015.gif)

**Comment by martpie** [comment]
Oh oh :see_no_evil: let me try to reproduce it
