### ISSUE TITLE
Suggestion: Double clicking playlist starts playing

### ISSUE THREAD

**Issue by MrDoctorKovacic** [martpie/museeks#495]
Great work, this app is beautiful and handles my 10K+ song library with no issues. Has become my goto Linux music player!

Small QOL change, could we make it so double clicking a playlist in the sidebar will start playing it? This feature is present in iTunes on MacOS.

I'll take a swing at adding it myself, but wanted to put it on the radar. Thanks!

**Comment by martpie** [comment]
Makes sense and should not be too hard to implement, I'll have a look!
