### ISSUE TITLE
Bug : When create playlist and add song to playlist have to restart app

### ISSUE THREAD

**Issue by modernduck** [martpie/museeks#504]
(Version 0.11.1 (0.11.1))

Hi When create playlist and add song to playlist; It didn't show up on playlist (but you could play whole playlist) But when I restart the app I could see list of tracks in the playlist again.

**Comment by martpie** [comment]
Thank you for the report, I'll investigate!

**Comment by modernduck** [comment]
> Thank you for the report, I'll investigate!

I think it happen  like this too
when you remove track in playlist to be zero  => then add new track => won't see track in playlist

**Comment by martpie** [comment]
Repro:

- Create new playlist
- Go to tracks list
- Add tracks to the playlist
- Go back to the playlist screen
- Playlist is not refreshed
