### ISSUE TITLE
Recusive folder searching (Like for itunes library)

### ISSUE THREAD

**Issue by codedcosmos** [martpie/museeks#510]
I don't think this will be to difficult to implement (unless it's a bug then it might be hard to track down).

I buy all my music on iTunes, copy it to my zfs partition and drag the folders into museeks under import music. Unfortunately it seems to only get files inside folders, and not files inside folders inside folders. Not loading 20% of my library, which I have to do largely manually. 

I assume the folder searching isn't recursive, and if it can be made to do so, that would be appreciated.

**Comment by codedcosmos** [comment]
Looking into it more I think it's an issue on my end, though I have no idea why. Il close until im certain otherwise.

**Comment by martpie** [comment]
Interested in the conclusion of this :) I never tested the app with zfs, and Node may have some problem with it.

**Comment by codedcosmos** [comment]
I cannot replicate what I experienced yesterday, it works perfectly on both ext4 and zfs. If the issue pops up again, I will make a new one issue with steps to reproduce, and reference it here.

I am not certain what was happening but at the moment it appears fine.
