### ISSUE TITLE
Bug: Song duration not detected + infinite progress bar

### ISSUE THREAD

**Issue by qcasey** [martpie/museeks#514]
I want to thank you for keeping this repo up to date!

On a very limited number of songs the duration is not detected, and the progress bar when playing these songs scales infinitely. I can look into both these issues since I have the files but I wanted to keep a tab of it here for easier merging.

![Screenshot from 2020-02-16 14-49-04](https://user-images.githubusercontent.com/1429672/74614737-5dc70d80-50cf-11ea-8cec-b4c4d74d4ae4.png)

**Comment by martpie** [comment]
Gotta say I laughed at the screenshot 😄 thank you for reporting these and submitting fixes 🙌
