### ISSUE TITLE
Remember tracks list scroll position when switching views

### ISSUE THREAD

**Issue by ldexterldesign** [martpie/museeks#519]
Hi!

Hope you're well

Thanks for wonderful software

As a user, when I switch/tab between Library, Playlist and Setting views, I want states to persist instead of defaulting to the top of the view (i.e. first track in list) so I don't have to scroll back to my previous state (e.g. a track half way down my list)

# Steps to reproduce issue

1. Click (i.e. play) a track in Library, preferably something one had to scroll the view to find
2. Navigate to another view (e.g. Playlists/Settings)
3. Navigate back to Library

# Unexpected behaviour

Library view shows top of view

# Expected behaviour

Library view shows the track I clicked to play before I left the view

If you're reading and:

* agree, then please vote up (e.g. +1, like), or;
* disagree, then please vote down (e.g. -1, dislike) - I'd love to know why?

If you have any issues (e.g. questions/queries) then happy to help

Keep up great work!

Sincerely

hardware: Apple, MacBook Pro (16-inch, 2019)
software - operating system: Apple, macOS, 10.15.3 (19D76)
software - application: Museeks, 0.11.3 (0.11.3)

**Comment by qcasey** [comment]
I completely agree, this would be nice

**Comment by qcasey** [comment]
What I found regarding react-router-dom:

https://reacttraining.com/react-router/web/guides/scroll-restoration/generic-solution

**Comment by martpie** [comment]
Scroll restoration won't work here as the scroll is not on the whole page but on a nested element.

I agree it should be done.

ps: careful with the phrasing, please don't be rude.

**Comment by ldexterldesign** [comment]
> ps: careful with the phrasing, please don't be rude.

As a [who], [when] [where], I [what] because/so [why] | foo #[type]

https://en.wikipedia.org/wiki/User_story#Principle

😁

**Comment by ldexterldesign** [comment]
🙏

UX is terrible for this ATM

Sincerely

**Comment by martpie** [comment]
a question for everyone here: do you want it to remember the scroll position? Or what you want is actually it automatically scrolls to the playing track?

**Comment by ldexterldesign** [comment]
Remember scroll position

Scroll to playing track is useful in some use cases but annoying in other use cases (e.g. I'm interacting with some non-playing tracks, adding to playlist etc. and then the view automatically scrolls away and I have to scroll back) so I would like an option for that

Hope this helps

Sincerely

**Comment by martpie** [comment]
Waiting on https://github.com/remix-run/react-router/pull/10468 to implement this. I'll definitely implement that as soon as the upstread PR gets merged and we have this available as a new API.
