### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by sudipghimire533** [martpie/museeks#520]
Why not making this able to play music from websites likesoundcloud, youtube, last.fm and so on.

**Comment by martpie** [comment]
Hello 👋 

> Museeks aims to be a simple and easy to use music player with a clean UI. You will not find tons of features, as its goals is not to compete with more complete and more famous music players. 

This is not really the goal to have a crazy amount of features. Last.fm integration is planned in #231 though, but only for scrobbling.

cheers!
