### ISSUE TITLE
Missing Linux dependencies

### ISSUE THREAD

**Issue by BlueManCZ** [martpie/museeks#524]
I'm just curious when I see these options in settings:
![Snímek z 2020-03-27 14-00-36](https://user-images.githubusercontent.com/17854950/77758581-82e65e80-7033-11ea-9b0e-14b198234991.png)
if Museeks shouldn't have `libappindicator`, `libxss`, `libxtst` or something like that in recommended dependencies?

**Comment by martpie** [comment]
Those features make use of APIs that are provided by Electron, so I would expect them to be installed when the app is installed 🤔 

But Linux's DEs are such a mess that you never really know what is already there, and if installing the dependencies will even make the feature work :x

**Comment by BlueManCZ** [comment]
I'm asking because I just created [ebuild](https://github.com/BlueManCZ/edgets/blob/master/media-sound/museeks-bin/museeks-bin-0.11.4.ebuild) in my overlay to provide Museeks to Gentoo users.

It's not so important I guess, but I can't test Museeks without these libraries, because I already have them installed in the system. Time will show.

**Comment by martpie** [comment]
Ah, interesting 🤔 

maybe these dependencies should be added there: https://github.com/martpie/museeks/blob/32f09584f5b501cca9d1a570b454ce584dbb3431/electron-builder.yml#L24

But we'd need to be sure to understand why they are not bundled with Electron. And if they are the correct name for all the Linux distros out there.

**Comment by BlueManCZ** [comment]
I know about these dependencies you mentioned. I found them in a .deb package.

And that missing dependencies should be provided as default by the common desktop environments, so It's probably not a big deal.

**Comment by martpie** [comment]
I could add a note in the README about these

**Comment by BlueManCZ** [comment]
Yea, something like:
> If you are experiencing troubles with Sleep mode blocker or Minimize to tray options, make sure you have ..... installed

**Comment by BlueManCZ** [comment]
And off-topic, when I mentioned ebuild, you can also add a note in the README about installing Museeks on Gentoo. Or should I create a pull request?

**Comment by martpie** [comment]
I don't know a lot about Gentoo and even less about ebuild. What is ebuild? their own .deb/.rpm/.AppImage?

**Comment by BlueManCZ** [comment]
Ebulid is text file, which says to package manager (Portage), how to extract and install the package into the system. You can specify a source file to download, in my case I used your .deb release on GitHub. Ebuilds are abstractions above manual extraction, (compilation) and installation.

**Comment by BlueManCZ** [comment]
In other words, when you don't have ebuild, you have to download .deb or .rpm package, extract it and place these files to proper locations. When you want to uninstall this, you have to keep notes which files you copied and where. Then find them and remove them.

When you have ebuild for this, all you have to do is type one command for installation and one for uninstallation. Package manager will handle it.

**Comment by BlueManCZ** [comment]
Ou, and I didn't mean you to explain that in README. :smile: 

Just something like:

## Installation
### Gentoo

Follow instructions [here](https://github.com/BlueManCZ/edgets).

would help Gentoo users to get what they want.

**Comment by martpie** [comment]
After some research, I have decided to kill the tray feature. See my rationale in #686 :)
