### ISSUE TITLE
5 requests on: Sorting, Adding, Re-scanning, Speed & Playlists

### ISSUE THREAD

**Issue by lottanbettan** [martpie/museeks#527]
* SORTING: In library view, if sorting tracks on any other than Title: it should still sort Title based on FILENAME starting on 0-9 (not only on id3 tag track number), so that the tracks are sorted by numbers even if the user sorts on Album.

* ADD MUSIC: It could be nice to be able to add new music to library by dropping files/folders directly in the library view.

* RE-SCAN: Add the possibility to reload/refresh/re-scan already added files, so that new id3 tags are updated, and deleted tracks (from disk) are listed as missing (or deleted from library?).

* SPEED: Are there any way to fix the slow start up time ("Loading library...")? Maybe it can load the library in chunks, and let the first chunk be small and then load the rest in the background?

* PLAYLISTS: The possibility to select/delete multiple playlists at once.

CHEERS

**Comment by martpie** [comment]
A year and a half later _whistling_

- Sorting: I consider it's the responsibility of the users to ensure their libraries hold the order on the album. Assuming anything on filesystem convention is never good, as it's so different for everyone.
- Add music from anywhere: I just added the feature yesterday (not released yet)
- Re-scan: it's planned #444, will do soon
- Speed: I'm thinking on switching back to another DB to make the load faster, I have to think about all this
- Playlists: Yeah I should maybe do that, but it's very painful to implement, so I'm not in a hurry. Opening a dedicated issue will help in keeping that in the backlog

cheers!
