### ISSUE TITLE
As a user I want keyboard shortcuts to navigate library/playlist/settings so I don't have to find those small buttons very close to my hot corners (macOS) #Enhancement

### ISSUE THREAD

**Issue by ldexterldesign** [martpie/museeks#528]
Hi all,

Hope you're well

Thanks for your great work

As title

It's a huge cursor distance to travel to those small buttons (i.e. library/ playlist/settings)

If these buttons don't have shortcuts or aren't made larger then I would argue they would be better suited to tabs at the top of the window, grouped with all the other high use features (e.g. player controls, search, track position (targeting this <=5px click target is a game in itself)).

I realise making things (i.e. click areas) larger can/does have wider design implications but it would improve UX a lot. If you're not already familiar with it then please have a look at [Fitts law](https://en.wikipedia.org/wiki/Fitts's_law).

I seriously think I'm getting repetitive strain injury from using these buttons 😢

Screen shot:

<img width="1792" alt="Screenshot 2020-04-23 at 02 45 33" src="https://user-images.githubusercontent.com/1715809/80047039-a4404a80-850c-11ea-8201-5928670d741c.png">

If you're reading and:

* agree, then please vote up (e.g. +1, like), or;
* disagree, then please vote down (e.g. -1, dislike) - I'd love to know why?

If you have any issues (e.g. questions/queries) then happy to help

Keep up great work!

Hope this helps and to hear back

Sincerely

**Comment by martpie** [comment]
I am thinking on moving this menu to a sidebar (à la iTunes), what do you think.

Regarding keyboard shortcuts, that could be something do-able.

**Comment by ldexterldesign** [comment]
> I am thinking on moving this menu to a sidebar (à la iTunes), what do you think.

Sure, I have no issues with how iTunes (now Apple Music) does it

Unsure if you use Notion (let me know if you don't and I'll do a screen cast) but they use a navigation sidebar and have a sticky option (i.e. always in view) or hide/show option (i.e. hidden until triggered, which is with a button and cursor position)

Keyboard shortcuts is a no brainer first step

Hope this helps

Sincerely
