### ISSUE TITLE
Add esc keyboard shortcut to clear & unfocus search input #Enhancement #Suggestion

### ISSUE THREAD

**Issue by ldexterldesign** [martpie/museeks#530]
Hi,

Hope you're well

Thanks for splendid software

As title

Annoying to have to move my cursor all the way to find that tiny x to clear search results, then move it back to whatever I was doing before searching (sometimes I even forget what I was doing)

A shortcut to input search queries (i.e. cmd + f) already exists so with an esc shortcut too it would make searches an instant thing rather than a taking seconds

Screen shot:

<img width="235" alt="Screenshot 2020-04-24 at 02 40 38" src="https://user-images.githubusercontent.com/1715809/80162961-05335580-85d5-11ea-8aab-5048d7fd1306.png">

If you're reading and:

* agree, then please vote up (e.g. +1, like), or;
* disagree, then please vote down (e.g. -1, dislike) - I'd love to know why?

If you have any issues (e.g. questions/queries) then happy to help

Keep great work!

Hope this helps

Sincerely

**Comment by martpie** [comment]
I am not sure to understand. Do you want a shortcut for when the input is not focused so it gets cleared? Or do you want an easy way to clear the input after using cmd-f?

**Comment by ldexterldesign** [comment]
Sorry I wasn't clear, and you've prompted me to think about this a bit more...

`cmd + f` should focus the input (as it does) and `esc` should unfocus the input (i.e. clearing input and returning my view to an unsearched/unfiltered state

Clearer?

Sincerely

**Comment by ldexterldesign** [comment]
Is this a [react] issue?

[react]: https://github.com/jaanauati/hyper-search/issues/74

**Comment by martpie** [comment]
But you can already cmd-f and it will select the text of the input for you, so you just to press "delete" and the selection is reset 🤔

**Comment by ldexterldesign** [comment]
Delete deletes one letter at a time. Do you mean `cmd + delete` (i.e. clears input)?

**Comment by ldexterldesign** [comment]
Delete is an option but it still doesn't unfocus the input which is the primary issue here I think

**Comment by martpie** [comment]
mmmh no. There is a rule (that may not be working for you) that when you select the input (via cmd-f or click), the text gets selected.

[Screen Recording 2020-04-24 at 11.14.43.mov.zip](https://github.com/martpie/museeks/files/4527812/Screen.Recording.2020-04-24.at.11.14.43.mov.zip)

Regarding the unfocus, I did not see any application where clearing the selection would clear the focus. It's not accessible nor intuitive if you want to type just after clearing the field.

**Comment by ldexterldesign** [comment]
I think you're correct

My mental model is how `cmd + f` functions in web browsers but that's a search not a filter

Have you considered renaming the "search" to "filter"?

Sincerely

**Comment by ldexterldesign** [comment]
I take it back

How do I get out of the search input without clicking out of it - there should be a keyboard shortcut for this?

**Comment by ldexterldesign** [comment]
Is tabbing out of the search input really the only way to get out of it using the keyboard without using cursor?

**Comment by ldexterldesign** [comment]
BUMP

**Comment by martpie** [comment]
Closing as wontdo as it's not a common pattern and would mean accessibility trouble. Clicking on the search input or using ctrl/cmd+F already select all the input text, which makes it trivial to clear, which I consider good enough.

Happy to be proven wrong in terms of accessibility issues.

**Comment by ldexterldesign** [comment]
All macOS apps
Bitwarden
Buttercup
Filen
Transmission
Visual Studio Code
Vivaldi
Warp

... pick one, they all do this:
> cmd + f should focus the input (as it does) and esc should unfocus the input (i.e. clearing input and returning the view to an unsearched/unfiltered state)

"Not a common pattern" 🤣

Stopped using your app years ago because of UX issues like this

Regards
