### ISSUE TITLE
Review/fix playlist export #Bug #Enhancement

### ISSUE THREAD

**Issue by ldexterldesign** [martpie/museeks#533]
Hi!

Hope you're well

Thanks for lovely software

As a user, when I attempt to export a playlist, I want successful exports even if a source file is missing (i.e. "show in file manager" file)

Unsure if this is a feature or not, but regardless the UX is a bit dodgy

# Steps to reproduce issue

1. Create a playlist
2. Add some files/tracks
3. Delete/move the files/tracks on the file system
4. (Attempt to )export playlist
5. Error

# Unexpected behaviour

Export fails, with not very helpful error message

# Expected behaviour

Export succeeds

.m3u shows all file paths, even if the files and/or file paths are updated/deleted in the file system or failing that a more descriptive error message

I guess this begs the (wider) question of how dynamically museeks links to files

Screen shot:

<img width="1792" alt="Screenshot 2020-05-05 at 16 51 08" src="https://user-images.githubusercontent.com/1715809/81081494-42abb300-8ef2-11ea-9d1a-9dc76eaf3525.png">

If you're reading and:

* agree, then please vote up (e.g. +1, like), or;
* disagree, then please vote down (e.g. -1, dislike) - I'd love to know why?

If you have any issues (e.g. questions/queries) then happy to help

Keep up sterling work!

Hope this helps & to hear back

Sincerely

hardware: Apple, MacBook Pro (16-inch, 2019)
software - operating system: Apple, macOS, 10.15.4 (19E287)
software - application: museeks, 0.11.4

**Comment by martpie** [comment]
Thanks for the report! Fixed in 1e922bf :)
