### ISSUE TITLE
Add auto option to light/dark theme setting (macOS) #Enhancement #Feature #Idea #Suggestion

### ISSUE THREAD

**Issue by ldexterldesign** [martpie/museeks#536]
Sorry for brevity, I think the title says it all

🤞

**Comment by martpie** [comment]
Ah Linux and its integration 🙄 😄 

There is currently a MPRIS integration in the player, do you know if MPRIS is supported by KDE? What system does KDE use to control music from the taskbar?

**Comment by ldexterldesign** [comment]
Sorry if i wasn't clear, I'm using macOS - what's this got to do with Linux?

Sincerely

**Comment by martpie** [comment]
oops sorry, wrong issue, got things mixed up

**Comment by martpie** [comment]
-> https://www.electronjs.org/docs/tutorial/dark-mode

**Comment by martpie** [comment]
Done in #595 :)
