### ISSUE TITLE
KDE Neon Media Player tray integration

### ISSUE THREAD

**Issue by derkan** [martpie/museeks#537]
Hi,
On **KDE Neon**, Museeks is not integrated with KDE's "**Media Player**" at tray.  Control buttons are disabled.

![image](https://user-images.githubusercontent.com/1723142/83966707-764c7500-a8c4-11ea-89a1-1ae2f9e08535.png)

Thanks

**Comment by martpie** [comment]
Ah Linux and its integration 🙄 😄

There is currently a MPRIS integration in the player, do you know if MPRIS is supported by KDE? What system does KDE use to control music from the taskbar?

**Comment by derkan** [comment]
I did a little search for MPRIS. I found these:

- Here is [KDE MPRIS wiki](https://community.kde.org/MPRIS)
- And [Clementine](https://github.com/clementine-player/Clementine/blob/4733185d08e78b8b1b43b154a5ef83251783e6c0/tests/mpris1_test.cpp) integrates well.

**Comment by martpie** [comment]
@derkan can you maybe try the version of Museeks that is now built on Linux? It may fix the mpris issue

https://github.com/martpie/museeks/actions/runs/444618423 -> at the bottom: "binaries-linux"

**Comment by martpie** [comment]
The last release should fix that :)
