### ISSUE TITLE
As a user, when a track can't be found, I want playback to continue (currently playback stops 😑 ) #Enhancement #Suggestion

### ISSUE THREAD

**Issue by ldexterldesign** [martpie/museeks#542]
Hi!

Hope you're well

Thanks for great software

As title

# Steps to reproduce issue

1. Create a playlist with 3 tracks
2. Delete track #2 from the file system
3. Play the playlist from track #1

# Unexpected behaviour

Playback will stop when track #2 is reached

# Expected behaviour

Playback simply skips track #2 and continues to track #3

As well as the existing global slippery notification I think a "track not found" local sticky error notification (e.g. an inline ⚠️ icon) would be useful too - for maintenance purposes perhaps this could even be a column so users can sort by broken tracks..?

Screen shot:

<img width="1904" alt="Screenshot 2020-08-13 at 01 23 05" src="https://user-images.githubusercontent.com/1715809/90080843-99036b80-dd03-11ea-851f-fbc060449cff.png">

If you're reading and:
* agree, then please vote up (e.g. +1, like), or;
* disagree, then please vote down (e.g. -1, dislike) - I'd love to know why?

Welcome feedback/input

If you have any issues (e.g. questions/queries) then happy to help

Keep up great work!

Hope this helps

Sincerely

software - OS: Apple, macOS, v10.15.6 (19G73)
software - application: museeks, v0.11.4 (0.11.4)

**Comment by martpie** [comment]
could not reproduce on the latest build 🤔 feel free to re-open if you still have that
