### ISSUE TITLE
tray icon does not appear in Gnome

### ISSUE THREAD

**Issue by alexxtasi** [martpie/museeks#551]
Hi there,
I am using `Solus 4.1 Fortitude` with `GNOME Shell 3.38.1`.
I just updated Museeks to version 0.11.4 ... using the AppImage method and since then when I close application's window:
- the tray icon does not appear
- I can still here music
- `museeks` process still runs and I have to kill it in order to close the app

processes are show here:
![museeks-run](https://user-images.githubusercontent.com/2122948/100881212-546c2d80-34b6-11eb-8e82-b8d042e81a8e.png)

any suggestions ?

**Comment by martpie** [comment]
Hello 👋 If you go back to a previous version of Museeks, do things work better?

**Comment by alexxtasi** [comment]
Didn't think of it!
I tested all versions back to `0.11.1` and all had the same issue.
So :
- in versions `latest`, `0.11.3` and `0.11.2`, gnome's tray icon want appear.
- in version `0.11.1` tray icon works fine !!

Strange ... in all versions I tested, my library worked the same way. Only in version `0.11.1` I had to re-add my testing library !!
Irrelevant but I mention it.

any thoughts ?

**Comment by martpie** [comment]
I could make a release with updated dependencies, this may fix it if there were breaking changes in the native libs in charge of notifications and tray

**Comment by alexxtasi** [comment]
It would be nice !! Thanks

.. and another irrelevant question (since I'm new here). Where can I find some kind of documentation on how Musseks works with library e.g - where does it save the library - does it write hidden files in the directory my files reside - does deleting from library affect files in any way ?
... or should fire an issue-question for this ?

**Comment by martpie** [comment]
On Linux, everything should be in `~/.config/museeks` (`$XDG_CONFIG_HOME/museeks`)

It includes the Library database (tracks + playlists basically) and the configuration file :) All your music files stay where they are.

**Comment by alexxtasi** [comment]
Happy to hear you ensure me of not touching my files :) it's the feature I seek for in a music app !!

I just tested the new version 0.11.5
The tray icon works fine !! Thanks

But there is another problem in the new version... not in the previous:
* there is no shortcut on Gnome. I only can run the app by bouble-clicking the appimage file

does anyone else has the same ?

regards

**Comment by martpie** [comment]
Mmmh that's weird, I haven't used Linux in a while, but I do remember that when opening an AppImage, it proposes you to create shortcuts on gnome no?

Did you try to clean the previous Museeks appimage before running the new one?

**Comment by martpie** [comment]
> Since electron-builder 21 desktop integration is not a part of produced AppImage file. AppImageLauncher is the recommended way to integrate AppImages.

Well, here's the answer, I guess I need to do that as well.

**Comment by alexxtasi** [comment]
> Did you try to clean the previous Museeks appimage before running the new one?

I did not delete them, just rename the files ... which I suppose isn't a problem.

**Comment by martpie** [comment]
Can you maybe try https://github.com/TheAssassin/AppImageLauncher ? It looks like it's the way to do desktop integration with AppImage now

**Comment by martpie** [comment]
Yeah I know, it's what I thought as well, but it looks like the "desktop integration" part is in a weird in-between state, where each part (AppImage or the app developer or the DE developers are saying "not my responsibility"). I haven't be using Linux as my daily driver for the last 3 years and a half, so I may be wrong somewhere.

Can the `.deb` or `.rpm` be a temporary alternative until I read more documentation on the subject?

**Comment by alexxtasi** [comment]
> Can the `.deb` or `.rpm` be a temporary alternative until I read more documentation on the subject?

For Solus system, no. It uses a complete different [packaging system](https://getsol.us/articles/package-management/basics/en/).

I just took a look on AppImage's documentation. It seem that [electron-builder ](https://www.electron.build/) is the one for Museek (it's electron app right ?). I have no electron background so I cannot do much things.

... so I will wait :)

**Comment by alexxtasi** [comment]
... quick feedback

I renamed Museeks folder directory (in my system is `~/.config/Museeks`) and run again the AppImage file from start.
It created a new directory as expected and tray icon and also Gnome's application shortcut worked !!!

**Comment by martpie** [comment]
What was the directory before the rename?

**Comment by alexxtasi** [comment]
Forgive me if I didn't make it clear.
The directory's name from the first time I used Museeks AppImage was `~/.config/Museeks/`.

In the latest test I renamed this directory, so running again AppImage it was created from the start (I suppose a delete would do the same).
Only then, the Gnome's shortcut worked as expected (Gnome's tray icon worked anyway with your `0.11.5` release).

**Comment by martpie** [comment]
Thanks for the clarification, weird behavior, but ok guess, at least your issue is resolved 😊

**Comment by martpie** [comment]
I will try to invest some time to see what is wrong, I think this can be closed in the meantime.
