### ISSUE TITLE
Suggestions/Requests

### ISSUE THREAD

**Issue by typhoon71** [martpie/museeks#552]
I was searching for a simple player for my family and this one fits the bill quite nicely (being crossplatform and all).

I've got some small suggestions for the interface (mostly).
I'm on windows, but museeks is also used on linux (mint mate and others).

- choose a default starting view (playlists or library window)
- customizable columns on playlists/library window (add/remove, move)
- remember last playing song (optionally restarting it on mouseeks launch)
- interface scaling (for hi-dpi screens, or just for older ppl)

Thanks.

**Comment by martpie** [comment]
Hello 👋

- Starting view -> Good idea, I think it makes a lot of sense
- Customizable columns -> #401 
- Last playing song -> #397 
- Interface scaling, this I'm surprised, it should be part of the OS no? Anyway, you can use ctrl/cmd +/- for these

**Comment by martpie** [comment]
Closing as issues exist for each point now :)

**Comment by typhoon71** [comment]
Really fast answer! 

Regarding the scaling: I asked because often OS scaling is not enough, in particular on older OS (say, windows 7) or some unix.
ie, on a windows7 device of mine, the shortcut doesn't do anything.
Btw: I asked for scaling because I supposed it's easier than skinning, which is something I would not ask (you know, like the "big" version of winamp -rip skins).

**Comment by martpie** [comment]
> the shortcut doesn't do anything.

mmh weird, I don't have a windows laptop with me right now, but could you maybe try the following? 

- press Alt
- it should display the application menu under the top window frame (I think)
- click on "view"
- click on zoom-in/zoom-out

**Comment by typhoon71** [comment]
Awww,  I was doing CTRL+ scroll, my bad.
Anyway, doing it using the menu option works perfectly, the issue is when usind the shortcut for zooming in (CTRL+SHIFT+=)
Also, can the shortcuts be more "intuitive", like using +/- along with modifiers? Just asking since we're on it.
