### ISSUE TITLE
Default view

### ISSUE THREAD

**Issue by martpie** [martpie/museeks#553]
Be able to chose between tracks and playlists view by default. Coming from #552.

**Comment by dreaddr** [comment]
Can there be a introduction splash screen when the app is first opened? 

Asking Interface preferences such as ("System Default", "Light mode" or "Dark mode" and between "Tracks" view and "Playlist view") from the first start and having the user choose them is much better IMHO.

It could also ask for the default directory, perhaps.

**Comment by martpie** [comment]
An on-boarding screen could be an interesting feature indeed, but it's a bit unrelated to this feature :)

**Comment by martpie** [comment]
Will work on that next :D
