### ISSUE TITLE
application menu application menu bug (windows)

### ISSUE THREAD

**Issue by typhoon71** [martpie/museeks#554]
The application menu doesn't get themed on windows: I enabled dark theme and it's still white.

Piggyback question: I see the menu disappears after you use it one time: can this became optional?
(not a big issue, just asking in case it's easy to implement)

**Comment by martpie** [comment]
I am not sure I have control over it, I will have to check.

**Comment by martpie** [comment]
-> Let's move this to #536

> I see the menu disappears after you use it one time

Looks like it should be easy to implement

**Comment by martpie** [comment]
Done in https://github.com/martpie/museeks/commit/d3c6789354cccc979a905c960c9dadc2b1487408

I think it makes sense indeed.
