### ISSUE TITLE
Modernize codebase

### ISSUE THREAD

**Issue by martpie** [martpie/museeks#555]
Before starting on new complex features, I would like to spend some time modernizing the codebase. The project was created with React 0.11 or something, and since, a lot of things changes, in best practices, APIs, etc.

Everything is on the table, from status quo to rewriting the whole thing.

Big ideas:

- [ ] And what about Next.js / Nuxt.js? Is it a good idea with Electron?
- [ ] If we stick with React: 
  - [ ] Move to FC, more hooks, less classes
  - [x] Get rid of Bootstrap completely, use Reakit for accessible components?
  - [x] Update ESLint rules
  - [x] Move to redux-toolkit
- [ ] Move more business logic to the main process
- [ ] Add tests
  - [x] ~Unit-tests for reducers (via Jest)~ setup done
  - [ ] Integration / E2E tests with Cypress
- [x] Create binaries on GitHub actions
  - [x] macOS code-signing
- [ ] Electron
  - [ ] Get rid of `electron.remote`
- ...

**Comment by YurySolovyov** [comment]
Wanna experiment with React Concurrent mode? :thinking:

**Comment by martpie** [comment]
I'm not really sure where it'd be useful in particular, we don't have CPU critical rendering (apart from the tracks list maybe)

**Comment by HaiDang666** [comment]
it really need tests since it helps new contributors to verify their code.

**Comment by chdg61** [comment]
Hello. 

What do you think about Cypress?

**Comment by martpie** [comment]
Cypress is the way to go for e2e tests right now, and I would not see myself using anything else.

The reason I'm not starting this big thing now is because I am thinking on a UI-focused update, and it would not make a lot of sense to write a lot of integration/e2e tests to update them just after this work is done.

**Comment by HaiDang666** [comment]
how about jest test for single component?

**Comment by martpie** [comment]
I don't believe in component testing (it's often really badly done).

Unit for utils/pure functions + e2e should be more than enough

**Comment by martpie** [comment]
Let's continue the discussion to #638. I am not planning on improving this more here right now.
