### ISSUE TITLE
Playlists aren't parsed due to `runk/node-chardet` 1.3.0 complaining about filesystem 

### ISSUE THREAD

**Issue by GilgameshxZero** [martpie/museeks#556]
The current version of `chardet` seems to consistently report an error: "File system is not available" when called on `src/ui/utils/utils-m3u.ts:11`, which causes playlists not to be imported correctly in release 0.11.5 as well as `master` branch.

I've only tested that this doesn't happen on `chardet 0.8.0`, but not sure if this holds for any other version of `chardet`  before the currently used `1.3.0`. A quick fix to this problem is to revert `chardet` to `0.8.0` in `package.json`. So, the last commit that I can guarantee works is <https://github.com/martpie/museeks/commit/834ace0a04c308ee3753339ce17a37a2f05fdf70>, but perhaps a few after that as well.

Chasing down the `chardet` package leads to the file <https://github.com/runk/node-chardet/blob/master/src/fs/node.ts> where `museeks` fails the conditional and thus throws the error. Something about package/module configuration is off? Or perhaps `chardet` makes invalid assumptions…

I don't have the time to chase down blame for this issue right now, so just marking it here for now. I think this error happens on all OS's.

**Comment by martpie** [comment]
I can reproduce it, thanks for noticing it 👍

**Comment by GilgameshxZero** [comment]
Correction to my previous post: the issue arises because `chardet` thinks that Electron is a browser environment and uses `https://github.com/runk/node-chardet/blob/master/src/fs/browser.ts` which just throws an error.

I opened an [issue](https://github.com/runk/node-chardet/issues/44) at `chardet` about this—I think some special-casing needs to be done for Electron environments, or the "browser" redirect in `chardet`'s `pakage.json` needs to be changed. We'll see if that issue goes anywhere I guess.

**Comment by martpie** [comment]
If this does not get fixed by `chardet`, we can move this logic to the main process

**Comment by runk** [comment]
https://github.com/martpie/museeks/pull/562
