### ISSUE TITLE
AudioVideo should be in categories in .desktop file

### ISSUE THREAD

**Issue by BlueManCZ** [martpie/museeks#565]
I'm getting this warning from Gentoo Quality Assurance:

```
 * QA Notice: This package installs one or more .desktop files that do not
 * pass validation.
 * 
 * 	/usr/share/applications/museeks.desktop: error: (will be fatal in the future): value item "Audio" in key "Categories" in group "Desktop Entry" requires another category to be present among the following categories: AudioVideo
 *
```

Could you append `AudioVideo` to the categories in .deskop file?

References: https://specifications.freedesktop.org/menu-spec/latest/apa.html
> Audio | An audio application | **Desktop entry must include AudioVideo as well**

**Comment by martpie** [comment]
Thank you for the deprecation notice 👍 will be fixed at the next release.
