### ISSUE TITLE
Publisher Verification

### ISSUE THREAD

**Issue by dreaddr** [martpie/museeks#570]
Needs publisher verification before I start sending this app to people I know, as most I know won't run an app from "Unknown sources" 

Honestly, the design could be improved as well if possible but my main concern is publisher verification for now. 

Currently using AIMP on Windows and Rhythmbox on Linux, but quite honestly I'd rather just have one app that just... plays music on any platform.

App does its intended function well from what I can experience, the potential is there, definitely looking forward to its' success. 👍

(Another suggestion, perhaps get it on the winget package manager after verification)

**Comment by martpie** [comment]
Windows certificates are too expensive. I'm ready to pay 100€ for an apple developer license, but I'm not ready to pay 400€ per year to sign Windows binaries.

So unless I find a way to monetize Museeks or someone is ready to pay for that, I won't be implementing it.

Hope you understand.

**Comment by dreaddr** [comment]
That is understandable, I wish the best of luck to this project as this is honestly a really good app as far as I can see.

Perhaps you would be eligible for an open source certificate like I found [here](https://shop.certum.eu/data-safety/code-signing-certificates.html)?

I'm not exactly sure how these would work, but if maybe it helps validate the app and spread it to garner support it would be worth it?
