### ISSUE TITLE
Previous/Next Media Items On Control Strip (MacBook Pro)

### ISSUE THREAD

**Issue by adudeongithub** [martpie/museeks#574]
The media items in the MacBook Pro Control Strip, with the exception of Pause/Play, are not working. It would be really great to be able to replay a song or fast forward through a playlist this way instead of always having to bring the player to the front or click and hold the icon in the dock and access the controls there.

Thanks for your work.

**Comment by martpie** [comment]
I can confirm that indeed, I guess it's the new controls from the latest macOS update. I will try to see how we can get the events from macOS to update the UI and the tracks when triggered.

**Comment by martpie** [comment]
#29376

**Comment by martpie** [comment]
ok, unfortunately you will need to add Museeks to the accessibility list in preferences > privacy. This should solve it.
