### ISSUE TITLE
Audio seek using left/right arrow keys

### ISSUE THREAD

**Issue by mike-seger** [martpie/museeks#575]
Hi Pierre

How about an audio seek as suggested here:

https://github.com/mike-seger/museeks/tree/audio-seek

Thanks a lot for your very nice and lean player.

Cheers
Mike

**Comment by jvegaf** [comment]
Congrats ! It's a great feat. Why you don't make a PR of that branch ?  

Regards

**Comment by jvegaf** [comment]
based in your idea, I implemented this feature using the keybinding component. 

https://github.com/jvegaf/museeks/commit/15c95b13780d3420e19b1fd25def17e464ecfc32

I'll try a make a PR.

**Comment by martpie** [comment]
Thank you @jvegaf ✅
