### ISSUE TITLE
Tray icon volume control

### ISSUE THREAD

**Issue by Winterhuman** [martpie/museeks#591]
Allowing the user to control the volume of Museeks using just the context menu of the tray icon, like how pavucontrol does it, would be a nice addition. It already has play, previous, and next options so volume control should fit in.

A full on volume bar would probably be too large, perhaps two buttons for volume up and down could be added in order to not increase the context menu's size drastically?

**Comment by martpie** [comment]
Hello 👋

Aren't you using the mpris module on Linux?

**Comment by LynHyper** [comment]
I was not aware of mpris and have just checked it out, it can address the issue, but, if play, previous, and next are already included in the context menu (even though mpris already covers those controls) why not add volume control alongside the existing controls that Museeks tray icon already has?

Not meaning to be demanding btw, just asking why some controls covered by mpris are included in the tray icon but not others.

**Comment by martpie** [comment]
So this is perfectly do-able and not to complex and a perfectly valid concern. The thing is tray menus tend to close once clicked. So to reduce a little bit the volume every time we click on "volume down" could get really tedious and not exactly the best user-experience.

I'd have to think a bit about this 🤔

**Comment by LynHyper** [comment]
Ah, I hadn't considered clicking would hide the context menu, that is difficult to get around unless some form of "inhibit close" option is available for tray icons (Not to mention if all platforms even have this option).

The main reason I want it included was I often times run Museeks in the background and then an extra loud or extra quiet song plays and I have to adjust the volume frequently, technically not as much as an issue once [this](https://github.com/martpie/museeks/issues/568) gets merged, but, that was my original reason for wanting this feature.

**Comment by LynHyper** [comment]
What about an "Open volume menu" which opens a separate window with just volume controls? That could solve the issue, but, it also adds an extra window which isn't ideal for the whole "keeping it minimal" goal.

**Comment by martpie** [comment]
Ah interesting! Thank you for the feedback. Can you thumb-up #568 ? So I can keep track of what users need/want :)

I'll try to see how hard it can be to implement

**Comment by LynHyper** [comment]
Sure thing! Eager to see Museeks improve in the near future

**Comment by LynHyper** [comment]
I think I'm willing to drop this issue if you want to, the pull request I mentioned earlier pretty much removes the need to adjust the volume of each next song when Museeks is minimised, I'll leave it to you to close in case you believe this is a worthwhile feature for the tray icon.

**Comment by martpie** [comment]
After some research, I have decided to kill the tray feature. See my rationale in #686 :)

**Comment by wefalltomorrow** [comment]
> After some research, I have decided to kill the tray feature. See my rationale in [#686](https://github.com/martpie/museeks/pull/686) :)

Craziness, the only reason I'm not switching to this music player is the lack of a tray feature :(

**Comment by martpie** [comment]
Can you explain what would be solved by a tray icon that is not solved by the MPRIS integration of your desktop environment?
