### ISSUE TITLE
Export fails on song move

### ISSUE THREAD

**Issue by LynHyper** [martpie/museeks#602]
If song files are moved to different locations, compared to where they were when they were added to the library, then Museeks won't be able to export playlists that contain those songs. The generic error message gives very little information as to why the export failed.

Changing the error message to something like "`Song name here` can't be found, Skip? [Skip | Cancel]" would be much more informative to the user.

Honestly not sure how Museeks should solve moving song files around though, seems tricky to do without introducing a lot more features thus going against it's minimalist philosophy, but, that's unrelated to the error message.

**Comment by LynHyper** [comment]
Nevermind, [this](https://github.com/martpie/museeks/releases/tag/0.12.0) release fixed the issue, it just hasn't made it to the AUR package yet.

**Comment by martpie** [comment]
:]

**Comment by martpie** [comment]
(I only publish binaries here, sometimes I update homebrew, but everywhere else, I don't really distribute the binaries, maybe one day I'll manage to automate all this)
