### ISSUE TITLE
Drop files on Museeks to add them to the library/playlist

### ISSUE THREAD

**Issue by Winterhuman** [martpie/museeks#606]
Not sure if this is already a planned feature for the upcoming redesign of Museeks so sorry if this is a duplicate, I didn't see any duplicate requests for this feature. 

Having the ability to drag songs into the playlist view to add songs to that playlist and the library would be a very welcome feature, it can be tedious to manually assign songs to playlists from the library when adding 100's of songs at once.

**Comment by martpie** [comment]
I am not sure to understand the feature, you would like to drag-and-drop songs from where to where? playlists to playlists? or library to playlists?

Because if the latter,  how would you chose in which playlist do you want to place the songs to go?

**Comment by LynHyper** [comment]
Let's say I have ten songs I want to be in Olaylist 1.

Currently, you'd add them to the library, selecting the ten songs in the library, and then assign them to Playlist 1. Instead, you'd go into playlist view, open Playlist 1 so you see the list of songs already in Playlist 1, and then drag-and-drop the ten songs into the list to add them to the library AND put them in Playlist 1 in one action.

**Comment by martpie** [comment]
Oh I see, I know there is another issue about something similar but I could not find it. The idea was to be able to add songs from any screen, but it did not have this idea of auto-adding them to the playlist, that's a cool idea, I'll close this one when I find the other issue, but let's keep it open in the meantime.

**Comment by martpie** [comment]
Managed to find some time to implement the first part of this, which is "Add files from anywhere". It does not add them to any playlist yet though.

https://user-images.githubusercontent.com/1311607/146761074-2c58a1a4-c645-4125-a21f-2e7f53f06817.mov

**Comment by Winterhuman** [comment]
Newest version of Museeks has added this, closing issue.
