### ISSUE TITLE
Feature Request: Seamless songs play (in album)

### ISSUE THREAD

**Issue by iliarostovtsev** [martpie/museeks#609]
Hi, Pierre.

Thank you again for the fantastic music player.

It would be great to have seamless songs play, when one solid album is being played, like _The Wall_ or _23 AM_ or any kind of those albums.

I suppose caching few first seconds of upcoming song would do it.

**Comment by martpie** [comment]
Hoi! It's the oldest issue opened :p https://github.com/martpie/museeks/issues/31

Pretty tricky to achieve, but it's really something I want to do!
