### ISSUE TITLE
Duplicate status tray items

### ISSUE THREAD

**Issue by LynHyper** [martpie/museeks#614]
I'm using Museeks v0.12.0, Arch Linux, and XFCE4 and noticed something bizarre.

Under **Status Tray Items**, the settings menu for the status tray plugin that comes with `xfce4-panel`, the **Known Items** section lists multiple items for Museeks named Museeks1, Museeks2, etc. No other application has duplicate items like this, even if only one Museeks item exists it will still be named Museeks1 which seems confusing to me, I'd be interested in seeing if other panel/trays exhibit this same behaviour.

I've tried replicating the issue by clearing known items, opening Museeks to create the Museeks1 item, and then rebooting to see if each Museeks item is a separate instance/session, but, this didn't cause any duplication. Neither did repeatedly quitting and starting Museeks.

My current theory is that each Museeks update is creating a new separate item, but, I haven't tested that to see if this is true.

EDIT: Just checked today and there are now two Museek items, I didn't have any Museeks update, but, I did get an `xfce4-session` update. However, even if `xfce4-session` was the cause, Museeks is the only one that duplicates items. I also personally doubt the update caused this since I had 7 duplicate items at one point, but, I've not had that many `xfce4-session` updates.

**Comment by martpie** [comment]
This might be related to this part of the code. I don't use Linux for my daily driver every day, so it's a bit hard for me to debug, but I'll try to have a look when I can.

https://github.com/martpie/museeks/blob/7c63a9f042bfededab86632d7f9d4f2da74911ad/src/main/modules/tray.ts#L55-L73

**Comment by martpie** [comment]
Let's continue the discussion on  #479
