### ISSUE TITLE
Museeks fails to open on Fedora 35

### ISSUE THREAD

**Issue by papasfilmsofficial** [martpie/museeks#615]
When installing using the **_.AppImage_** file (or the **_.rpm_**. I have tried both) the program exits with this error code:
![Screenshot from 2021-12-06 16-32-31](https://user-images.githubusercontent.com/50630783/144864582-d03f1a2f-138e-4247-bb71-622bb931c199.png)

**Comment by martpie** [comment]
I lol'ed when I saw the "goodbye" error 😄

It looks like you have no GPU or something? Do you have the correct drivers installed if needed? (like nvidia drivers?). Also, do you know if you can open any other electron app? (like VSCode, Atom...)?

**Comment by genzyy** [comment]
> When installing using the **_.AppImage_** file (or the **_.rpm_**. I have tried both) the program exits with this error code: ![Screenshot from 2021-12-06 16-32-31](https://user-images.githubusercontent.com/50630783/144864582-d03f1a2f-138e-4247-bb71-622bb931c199.png)

Did you try installing a newer version of `libcurl`? or maybe try running `museeks --trace-deprecation`. We need more data on this.

Also mention whether you are using `X11` or `Wayland`.

**Comment by papasfilmsofficial** [comment]
After leaving my computer idle for around 2-3h I tried launching it again (without a reboot) and it magically decided to open! Yes, I have the latest nvidia drivers available and everything is up to date.
