### ISSUE TITLE
Sort by Track Number

### ISSUE THREAD

**Issue by Martajnez** [martpie/museeks#622]
Hello museeks community. I really like using this app on my Linux system, although I think that it's missing one, very important feature - sorting by track number.  Because of that, listening albums in proper order (as far as I know) is impossible.  Is this possible to implement?

Regards, Martin.

**Comment by martpie** [comment]
Tracks are already sorted by track number. There is one bug that would sometimes mess with album order for tracks with multiple artists, but it is fixed in `master` and will be released at some points soon.

Do you have a screenshot to share? More explanation on your issue?

**Comment by Martajnez** [comment]
No way. I just opened museeeks and sorting works perfectly.  ;-; Forget about it 😅 Have a nice day!
