### ISSUE TITLE
Suggestion: MacOS menu/control center better detail

### ISSUE THREAD

**Issue by tbjgolden** [martpie/museeks#624]
<img width="313" alt="Screenshot 2021-12-27 at 00 05 23" src="https://user-images.githubusercontent.com/8162045/147423082-3892cbdc-6c29-44bc-9894-604a4a6cba54.png">

This screenshot shows both how IINA appears when playing a song and how Museeks currently appears when playing a song - it would be useful to know which song is playing (+ artist, + album art if we're brave)

**Comment by martpie** [comment]
Not sure if this is in my control, but absolutely, we should implement it!

**Comment by martpie** [comment]
Looks easily do-able 👍

https://stackoverflow.com/questions/60987650/electron-how-to-control-system-media-play-pause

```js
navigator.mediaSession.metadata = new MediaMetadata({
    title: "Title",
    artist: "Artist",
    album: "Album",
    artwork: [
        { src: "example.com", sizes: "192x192", type: "image/png" }
    ]
});
```
