### ISSUE TITLE
Not opening in fedora 35

### ISSUE THREAD

**Issue by ivex001** [martpie/museeks#630]
Hi there, i was about to try this player but it doesn't open. when opening in terminal i got the following error:

[INFO] Skipping load of ThumbarModule
[INFO] Skipping load of DockMenuDarwinModule
(node:6498) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `museeks --trace-deprecation ...` to show where the warning was created)
[6498:0106/175140.347742:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Armadilha de rastreio/ponto de quebra (núcleo despejado)

**Comment by martpie** [comment]
Similar to https://github.com/martpie/museeks/issues/615#issuecomment-986943203

Try restarting or making sure your drivers are correctly loaded, if it still happens I'll re-open it.

**Comment by ivex001** [comment]
I've restarted and the problem persist. The drivers are loaded correctly as far as i know. The only difference is that im using nvidia as primary GPU on optimus-based laptop:

gpu driver: NVIDIA GeForce GTX 850M/PCIe/SSE2
kernel: x86_64 Linux 5.10.89-200.fc35.x86_64

**Comment by martpie** [comment]
can you try `museeks --disable-gpu-sandbox`?

**Comment by martpie** [comment]
Related:

https://github.com/electron/electron/issues/32074
https://github.com/electron/electron/issues/31123

**Comment by ivex001** [comment]
> can you try `museeks --disable-gpu-sandbox`?

Yes using this flag worked fine.  Thanks for your support

**Comment by martpie** [comment]
So this is kind of an upstream bug where everyone will deny responsibility for this bug. I'll send it to Electron, Electron will send it to Fedora, Fedora will send it to x11, x11 will send it to...

**Comment by ivex001** [comment]
Probably X11 il send it to nvidia too.

**Comment by martpie** [comment]
Closing as stale. If this is still happening with the latest version of Museeks, please ping me!
