### ISSUE TITLE
different cover between dev env and download app

### ISSUE THREAD

**Issue by noob000** [martpie/museeks#631]
in download app when play a music:
![image](https://user-images.githubusercontent.com/67864329/148525522-bb2e5cf6-72ff-4cf5-924f-0f64dcb9587a.png)
![image](https://user-images.githubusercontent.com/67864329/148525638-c19e22b9-e6aa-4393-9efd-5ef02aa5c43d.png)
in electron dev env:
![image](https://user-images.githubusercontent.com/67864329/148526058-79344732-88d7-42e6-9828-04e38dfdad8e.png)
![image](https://user-images.githubusercontent.com/67864329/148526085-b393fc80-6053-482f-95b0-1f3fd93fd0b0.png)

Could you tell me what cause the differences?thanks a lot

**Comment by martpie** [comment]
It's because I added this feature during this Christmas holiday, but I haven't drafted a release yet :)

Will be released in 0.13 (hopefully soon)
