### ISSUE TITLE
"Add to queue" is not always available

### ISSUE THREAD

**Issue by beninsydney** [martpie/museeks#632]
The option to "Add to queue" appears to be dependent on having a song currently playing or a queue of songs but when those conditions are not met, shouldn't the default be to create a new queue with the selected song(s)?

I have been experimenting with this and found where an option could be added in `TrackList.tsx`:

https://github.com/martpie/museeks/blob/master/src/renderer/components/TracksList/TracksList.tsx#L372

But I've been having trouble making it re-render the queue after adding the selected - 

      if (playerStatus !== PlayerStatus.STOP) {
        addToQueueTemplate = [
          {
            label: 'Add to queue',
            click: async () => {
              await QueueActions.addAfter(selected);
            },
          },
          {
            label: 'Play next',
            click: async () => {
              await QueueActions.addNext(selected);
            },
          },
          {
            type: 'separator',
          },
        ];
      } else {
        // the added code
        addToQueueTemplate = [
          {
            label: 'Add to queue',
            click: async () => {
              await QueueActions.addNext(selected);
            },
          }
        ];
      }

**Comment by martpie** [comment]
Done in [f2f55dc](https://github.com/martpie/museeks/commit/f2f55dc83db235c62292810ce681370cf5fdbaa8), thanks for the suggestion :)
