### ISSUE TITLE
can't install on Fedora 35

### ISSUE THREAD

**Issue by rafadesign** [martpie/museeks#635]
I'm trying to install Museeks on Fedora, but it conflicts with Local WP which is a software that allows you to use wordpress locally

![Captura de tela de 2022-05-06 19-38-51](https://user-images.githubusercontent.com/46974593/167224727-ae58a205-55ae-4017-97b0-07cf9df59360.png)

**Comment by martpie** [comment]
Have you tried installing the binary directly? https://museeks.io/ I am not maintaining the distribution on Fedora directly

**Comment by rafadesign** [comment]
> ‎Você já tentou instalar o binário diretamente? ‎[‎https://museeks.io/‎](https://museeks.io/)‎ Eu não estou mantendo a distribuição em Fedora diretamente‎

I downloaded the .rpm file directly from the website

**Comment by martpie** [comment]
Can you provide more information on your setup? Fedora version, etc?

**Comment by rafadesign** [comment]
> ‎Você pode fornecer mais informações sobre sua configuração? Versão fedora, etc?‎

![Captura de tela de 2022-05-07 14-18-10](https://user-images.githubusercontent.com/46974593/167264912-49e0b911-58f0-4c08-a41f-87f408f01486.png)

**Comment by martpie** [comment]
I have a small release to make soon (I've been delaying it forever), it may fix it, I'll ping you when it's ready

**Comment by martpie** [comment]
Does the latest release fixes it?
