### ISSUE TITLE
Mouse Over Volume Control Displays Volume Slider Over Previous/Pause/Next Buttons

### ISSUE THREAD

**Issue by highschooldropout** [martpie/museeks#642]
Accidentally mousing over the volume control displays the volume slider on the left side, over the previous/pause/next buttons. Perhaps this would be better placed on the right side. Minor inconvenience but an aesthetic and functional consideration nonetheless.

![slider](https://i.ibb.co/rmMJmtN/slider.gif)

**Comment by martpie** [comment]
This is a known UX issue #351 

I will fix it on a new UI revamp I'm working on (via #639 and #640) (feedback welcome)
