### ISSUE TITLE
Playlist view shows "Your search returned no results"

### ISSUE THREAD

**Issue by Winterhuman** [martpie/museeks#646]
Museeks v0.13.0

The playlist view states "Your search returned no results", however, the playlists do have tracks in them; switching between the playlists shows the actual tracklist for a fraction of a second before the no-results screen appears instead.

Using the search bar in the top-right doesn't change the result, the tracklist still only appears for a brief moment (though the tracklist does seem to be filtered).

**Comment by blackshibe** [comment]
Fixed in https://github.com/martpie/museeks/pull/648

Reproduced it like this: 
- Open app
- Open playlists view
- Open main app view
- Open playlists view again

**Comment by raphial** [comment]
I'm having the exact same issue after updating from 0.12 to 0.13 via .deb package on Linux Mint 20.2 (Based on Ubuntu). I did not have this issue in 0.12. Playlists appear fine opening the app, but the moment I shift through them, they start having their content disappear with the "Your search returned no results" error, even tho the song file is still playing in the playlist, and the files are still there. 

Library still shows all my music, however.

**Comment by martpie** [comment]
Yes sorry, there's a fix and I need to release it, thank you for pinging the issue again 🙇‍♂️

**Comment by raphial** [comment]
> Yes sorry, there's a fix and I need to release it, thank you for pinging the issue again bowing_man

You're the man! Unfortunately updating cleared my library and all of my playlists. I had to reupload backed up .m3u playlist files I had. I'm not sure if this is normal behavior either. I lost roughly 120+ songs in these playlists x.x

I'll downgrade back to 0.12 in the meantime. Thanks for the quick response!

**Comment by Winterhuman** [comment]
Yeah, v0.13 introduced the issue, v0.12 was fine

**Comment by martpie** [comment]
Fixed and released in 0.13.1
