### ISSUE TITLE
More sort options

### ISSUE THREAD

**Issue by blackshibe** [martpie/museeks#647]
I migrated from spotify to museeks a while ago, and I still miss being able to sort by the date added, as the way I used to listen to music would be mainly on loop in the liked songs playlist. It would make sorting through new music much easier without manually creating playlists. 

Considering there isn't enough space for more information in the current list sort, a context menu would probably work?
![image](https://user-images.githubusercontent.com/57596776/174761767-1dabbddb-340c-4410-bc58-3ff134c657ea.png)

**Comment by martpie** [comment]
This enhancement is tracked there -> #401 :)

tldr: not implemented yet because it's not possible to resize columns yet, and re-sizing columns is quite a shift as it can overflow from its container (meaning we'll have to introduce horizontal scrolling)
