### ISSUE TITLE
Start volume at 50%

### ISSUE THREAD

**Issue by Winterhuman** [martpie/museeks#654]
When starting a song for the first time, having the volume at 100% can be very... surprising. This is possibly related, or superceded, by https://github.com/martpie/museeks/issues/568

**Comment by martpie** [comment]
We set the volume at 1, which should be the same as anywhere else (youtube using chrome or firefox or else), or any other player not harmonizing volume directly. 🤔 we do not pre-amplify anything

**Comment by Winterhuman** [comment]
Ah no, I mean the volume bar itself starts all the way to the right, but it should ideally be in the middle so it's only using half of the possible volume

**Comment by martpie** [comment]
Can you share one of those files that is really loud?

**Comment by Winterhuman** [comment]
All the songs I have are from what I can tell

**Comment by martpie** [comment]
Can you tell me more about your setup? (os, etc)

**Comment by Winterhuman** [comment]
Okay, I think I found the problem. I've always set my system volume quite high so everything ends up being loud, except for a few things which require me to bump up the max volume otherwise, and I've only just noticed what I've been doing.

I think I have a better solution though, I'll open a new issue for it.
