### ISSUE TITLE
Remember volume level on restart

### ISSUE THREAD

**Issue by Winterhuman** [martpie/museeks#656]
Related: https://github.com/martpie/museeks/issues/654

Letting Museeks remember what the volume level was between restarts would be a useful feature, sometimes people set their system volume quite high for certain apps/media (like me as I found out) and have to turn down the volume for all other apps, caching the volume level would help with this scenario.

**Comment by martpie** [comment]
Museeks does remember the volume value, but there's actually an issue on restart when the non-eased value is used instead of the eased one, this I can fix.

**Comment by martpie** [comment]
Fxied in 286652a
