### ISSUE TITLE
Last.FM integration

### ISSUE THREAD

**Issue by rorcores** [martpie/museeks#658]
I see this has been discussed in the past but dismissed due to feature creep. I understand that but unfortunately a deal breaker for a lot of people. It's such a lightweight and easily toggle-able feature. Any chance we can bring this issue back up?

**Comment by martpie** [comment]
> It's such a lightweight and easily toggle-able feature

unfortunately no, it requires opening a browser window to login, registering the app on the file association system so the browser can send the api key back to the app, store the api key in a secure-enough way, etc. So it's a little bit non trivial.

see #231 for more details

**Comment by rorcores** [comment]
I didn't mean non-trivial from a build perspective, I meant non-trivial from a 'product bloat' perspective. But no worries - I'll try a different product, thanks.
