### ISSUE TITLE
Not in traybar when minimized

### ISSUE THREAD

**Issue by PhilJbt** [martpie/museeks#664]
Museeks is not displayed in the system tray bar when minimzed.

<br/>

- Museek 0.13.1 x64 Portable
- Museek 0.13.1 x64 Setup

<br/>

- Windows 10 22H2 19045.2251
- Windows Feature Experience Pack 120.2212.4180.0

<br/>

[2022-11-14 09-36-07.webm](https://user-images.githubusercontent.com/22506952/201614067-50b92f8b-884c-40a0-b3b8-1475a132f511.webm)

**Comment by martpie** [comment]
test

**Comment by martpie** [comment]
I can reproduce, thank you, I will fix it asap

**Comment by martpie** [comment]
After some research, I have decided to kill the tray feature. See my rationale in #686 :)
