### ISSUE TITLE
Auto add music when file added to folder without manually add files

### ISSUE THREAD

**Issue by dipras** [martpie/museeks#680]
When we attach a folder, the app will listing all the music inside the folder. But the problem is when the folder is already attached and we add another music to it, the music not auto added to our library. If we want to add it to library, we must reset the library and attach the folder again
We need the app to re-scan attached folder if there new music when we open the app

**Comment by jpufferfish** [comment]
similar to #444. I'd also like this feature

**Comment by martpie** [comment]
Yep, let's discuss on #444 which has more context on why it's tricky :)
