### ISSUE TITLE
☂️ 0.14 bucket list

### ISSUE THREAD

**Issue by martpie** [martpie/museeks#693]
0.14 does not bring a lot of improvements, but things under the hood were considerably changed. This tracks a list of known issues that broke since all those changes.

- [x] adding tracks don't refresh the library anymore
- [x] migrate off linvodb #696 
- [x] fix theme update
- [x] make sure scrollbar is dark on windows/linux with dark mode
- [ ] start button with no queue does not work anymore (hard-ish to solve)
- [x] deleting the current playlist crashes the app
- [x] 4100 / 4038 scanned
- [x] separator between select tracks is gone (and annoying to fix)
- [x] fix ipc events not caught by  renderer
- [x] fix max_event_listeners from renderer
- [x] adding tracks to library sometimes hangs?
- [x] chores: infer loader data shape from loader return type #725

**Comment by dipras** [comment]
I tried some test about scrollbar color according to #695 
I found new bug where the theme is not auto rerender when we change it and need to restart the application to render change

https://github.com/martpie/museeks/assets/51155424/6e04b236-3427-491f-922a-64dfda5abc42

FYI, here is my device specification
![image](https://github.com/martpie/museeks/assets/51155424/8691a325-059f-4181-acf6-4d2111cb002a)

**Comment by martpie** [comment]
Closing, see #748 for what's left.
