### ISSUE TITLE
[QUESTION] Scrollbar in master

### ISSUE THREAD

**Issue by dipras** [martpie/museeks#695]
So when i try master branch i notice something, the scrollbar is different from latest release

![Screenshot_20230630_195744](https://github.com/martpie/museeks/assets/51155424/45d1bb7b-3ea8-4fdf-a202-82d18dc1153c)

So i tried to compare the code and look like you removed `<CustomScrollbar>` from `TrackList.ts`
I just want to ask, are you remove the custom scrollbar for some reason or it's only because you migrated from renderView to Virtuoso and not yet implement the custom scrollbar?

**Comment by martpie** [comment]
Hey 👋
This is Linux right?
I've done quite a bit of simplification to use more native elements, but I could not test them everywhere yet. I added that to the 0.14 bucket list on  #693.
There's something to be checked here: https://www.electronjs.org/docs/latest/tutorial/dark-mode#automatically-update-the-native-interfaces

**Comment by martpie** [comment]
If you're interested in debugging it:

the backend part is here: https://github.com/martpie/museeks/blob/a423a5a8ddc85b0b56aadfa300df90107c4ce2ca/src/main/modules/NativeThemeModule.ts#L65-L87

the frontend (I suspect `prefers-color-scheme` might help):

https://github.com/martpie/museeks/blob/a423a5a8ddc85b0b56aadfa300df90107c4ce2ca/src/renderer/stores/SettingsAPI.ts#L16-L42

**Comment by martpie** [comment]
@dipras I have just pushed a fix that works on Windows, can you tell me if it works with your Linux DE? (last commit on master)

**Comment by dipras** [comment]
> @dipras I have just pushed a fix that works on Windows, can you tell me if it works with your Linux DE? (last commit on master)
![Screenshot_20230701_013836](https://github.com/martpie/museeks/assets/51155424/32aa33a0-1cd8-475f-9cde-ede0f312e1b3)

Thank, it's now fixed

**Comment by martpie** [comment]
awesome!
