### ISSUE TITLE
Notorization issue on macOS M1

### ISSUE THREAD

**Issue by ehyoitsdavid** [martpie/museeks#736]
When I try to open the app the following screenshot shows and the app cannot be opened.
Most possibly related to notorisation issue.
![Screenshot 2023-12-13 at 8 53 08 AM](https://github.com/martpie/museeks/assets/106898439/5dec51bd-5794-4c63-a43a-951fa613350f)

See also https://support.apple.com/en-ca/HT202491

**Comment by nrthbound** [comment]
Any updates or workarounds for this? Thanks.

**Comment by martpie** [comment]
You can right-click on Museeks -> Open -> Open Anyway.

You can also follow the steps here: https://support.apple.com/en-gb/guide/mac-help/mchleab3a043/mac

I will fix the certificate not being correctly applied in the next release.
