### ISSUE TITLE
macOS: Can't make Museeks automatically open FLAC files

### ISSUE THREAD

**Issue by slajerek** [martpie/museeks#746]
When I select in Finder a flac file and then select open with, the Museeks is not available to set as default for flac files. 
Museeks can not be set as default application to open flac files. If I force that then anyway the file is not opened in Museeks.

<img width="648" alt="Screenshot 2024-03-02 at 12 36 02" src="https://github.com/martpie/museeks/assets/1021783/a6e3dc7a-bd53-4f72-90df-748f31990ea4">

**Comment by martpie** [comment]
Yes, playing files from finder/export (=without them being in the DB) is not supported yet, see duplicate #154 

I hope with #745 I will be able to make it work more easily than Electron :)
