### ISSUE TITLE
Tracks From Album Appear Out Of Order

### ISSUE THREAD

**Issue by foglabs** [martpie/museeks#777]
![Screenshot 2024-08-05 at 3 18 23 PM](https://github.com/user-attachments/assets/b28d44cf-be23-4be2-95b6-aff0118f1cfb)

Attached screenshot shows tracks 15 and 16 (the bonus tracks) showing up at the beginning of this album, when these two tracks should be at the end of the album. Track metadata has the correct sequential track number values for these tracks. Clicking 'album' label to reverse order does not change the displayed track order. This is on macOS Ventura 13.4.1.

Thanks!

**Comment by foglabs** [comment]
sure I can google drive them to you on your gmail if that works! thanks for getting back to me

**Comment by martpie** [comment]
Sounds perfect!

**Comment by martpie** [comment]
Interestingly enough, Music (ex-iTunes) sort by Alphabetical order (minus "The"). In a way, that makes sense, as people are more susceptible to know the name of their album than their year of release 🤔

![Screenshot 2024-09-04 at 17 25 51](https://github.com/user-attachments/assets/a4fb4b85-77ee-4bc0-8904-6bd63b7f988d)

**Comment by foglabs** [comment]
hmm, I would want the tracks within albums to be sorted by track number. in any case, thanks for responding to my issue!

**Comment by martpie** [comment]
I think this is a change that makes sense :)
