### ISSUE TITLE
"See more" button in Queue

### ISSUE THREAD

**Issue by martpie** [martpie/museeks#92]
That'd be great to have the possibility to see more tracks in the queue.

**Comment by cfollet** [comment]
Isn't the scrolling sufficient?

**Comment by YurySolovyov** [comment]
kind of, but ATM you can scroll to the end of the queue, it it is much shorter than actual playlist/library

**Comment by KeitIG** [comment]
> Isn't the scrolling sufficient?

We won't display 3000 tracks if there's 3000 tracks in the queue. This would implies to do a dynamic loading like what I did for TracksList. Another solution of course is dynamically load 20 more after a certain scroll.

**Comment by cfollet** [comment]
Scrolling is more accessible than mixing scroll & button IMO. I do not recommend to do that feature with a button, think about 3000 tracks displayed 50 per 50 for example.

**Comment by KeitIG** [comment]
That's true, but usually you should not need to access the 3000th track. I copied that behavior from iTunes. I'm fine with a scroll :)
